tag @s remove armor_leather
tag @s remove armor_leatherE
tag @s remove armor_copper
tag @s remove armor_copperE
tag @s remove armor_chainmail
tag @s remove armor_chainmailE
tag @s remove armor_gold
tag @s remove armor_goldE
tag @s remove armor_iron
tag @s remove armor_ironE
tag @s remove armor_diamond
tag @s remove armor_diamondE
tag @s remove armor_netherite
tag @s remove armor_netheriteE
tag @s remove vip_enchanted_gold_armor
tag @s remove vip_enchanted_gold_armorE
tag @s remove megavip_god_armor
tag @s remove megavip_god_armorE

tag @s remove pickaxe_wooden
tag @s remove pickaxe_woodenE
tag @s remove pickaxe_copper
tag @s remove pickaxe_copperE
tag @s remove pickaxe_stone
tag @s remove pickaxe_stoneE
tag @s remove pickaxe_gold
tag @s remove pickaxe_goldE
tag @s remove pickaxe_iron
tag @s remove pickaxe_ironE
tag @s remove pickaxe_diamond
tag @s remove pickaxe_diamondE
tag @s remove pickaxe_netherite
tag @s remove pickaxe_netheriteE
tag @s remove vip_enchanted_gold_pickaxe
tag @s remove vip_enchanted_gold_pickaxeE

tag @s remove shovel_wooden
tag @s remove shovel_woodenE
tag @s remove shovel_copper
tag @s remove shovel_copperE
tag @s remove shovel_stone
tag @s remove shovel_stoneE
tag @s remove shovel_gold
tag @s remove shovel_goldE
tag @s remove shovel_iron
tag @s remove shovel_ironE
tag @s remove shovel_diamond
tag @s remove shovel_diamondE
tag @s remove shovel_netherite
tag @s remove shovel_netheriteE

tag @s remove sword_wooden
tag @s remove sword_woodenE
tag @s remove sword_copper
tag @s remove sword_copperE
tag @s remove sword_stone
tag @s remove sword_stoneE
tag @s remove sword_gold
tag @s remove sword_goldE
tag @s remove sword_iron
tag @s remove sword_ironE
tag @s remove sword_diamond
tag @s remove sword_diamondE
tag @s remove sword_netherite
tag @s remove sword_netheriteE

tag @s remove axe_wooden
tag @s remove axe_woodenE
tag @s remove axe_copper
tag @s remove axe_copperE
tag @s remove axe_stone
tag @s remove axe_stoneE
tag @s remove axe_gold
tag @s remove axe_goldE
tag @s remove axe_iron
tag @s remove axe_ironE
tag @s remove axe_diamond
tag @s remove axe_diamondE
tag @s remove axe_netherite
tag @s remove axe_netheriteE

tag @s remove spear_wooden
tag @s remove spear_woodenE
tag @s remove spear_copper
tag @s remove spear_copperE
tag @s remove spear_stone
tag @s remove spear_stoneE
tag @s remove spear_gold
tag @s remove spear_goldE
tag @s remove spear_iron
tag @s remove spear_ironE
tag @s remove spear_diamond
tag @s remove spear_diamondE
tag @s remove spear_netherite
tag @s remove spear_netheriteE

tag @s remove potion_speed
tag @s remove potion_speedE
tag @s remove potion_jump
tag @s remove potion_jumpE
tag @s remove potion_strength
tag @s remove potion_strengthE
tag @s remove potion_health
tag @s remove potion_healthE
tag @s remove potion_damage
tag @s remove potion_damageE
tag @s remove potion_poison
tag @s remove potion_poisonE
tag @s remove potion_wither
tag @s remove potion_witherE
tag @s remove potion_regeneration
tag @s remove potion_regenerationE
tag @s remove potion_turtlemaster
tag @s remove potion_turtlemasterE
tag @s remove potion_invisibility
tag @s remove potion_invisibilityE

tag @s remove block_grass
tag @s remove block_grassE
tag @s remove block_glass
tag @s remove block_glassE
tag @s remove block_planks
tag @s remove block_planksE
tag @s remove block_dev
tag @s remove block_devE
tag @s remove block_leaves
tag @s remove block_leavesE
tag @s remove block_cobblestone
tag @s remove block_cobblestoneE
tag @s remove block_wool
tag @s remove block_woolE
tag @s remove block_obsidian
tag @s remove block_obsidianE
tag @s remove vip_rgb_blocks
tag @s remove vip_rgb_blocksE

tag @s remove equipment_bow
tag @s remove equipment_bowE
tag @s remove equipment_shield
tag @s remove equipment_shieldE
tag @s remove equipment_totem
tag @s remove equipment_totemE
tag @s remove equipment_snowball
tag @s remove equipment_snowballE
tag @s remove equipment_fishing_rod
tag @s remove equipment_fishing_rodE
tag @s remove equipment_flint_and_steel
tag @s remove equipment_flint_and_steelE
tag @s remove equipment_shears
tag @s remove equipment_shearsE

tag @s remove vip_ender_pearl
tag @s remove vip_ender_pearlE
tag @s remove vip_wind_charge
tag @s remove vip_wind_chargeE
tag @s remove vip_golden_apple
tag @s remove vip_golden_appleE
tag @s remove vip_enchanted_golden_apple
tag @s remove vip_enchanted_golden_appleE

tag @s remove megavip_trident
tag @s remove megavip_tridentE
tag @s remove megavip_elytra
tag @s remove megavip_elytraE
tag @s remove megavip_mace
tag @s remove megavip_maceE
tag @s remove megavip_gluon_gun
tag @s remove megavip_gluon_gunE
tag @s remove megavip_tau_cannon
tag @s remove megavip_tau_cannonE
tag @s remove megavip_hive_hand
tag @s remove megavip_hive_handE

tag @s remove vip
tag @s remove mega_vip

tag @s remove purple_cage
tag @s remove purple_cageE
tag @s remove fire_cage
tag @s remove fire_cageE
tag @s remove dev_cage
tag @s remove dev_cageE
tag @s remove nether_cage
tag @s remove nether_cageE
tag @s remove fish_tank_cage
tag @s remove fish_tank_cageE
tag @s remove amethyst_cage
tag @s remove amethyst_cageE
tag @s remove cherry_blossom_cage
tag @s remove cherry_blossom_cageE
tag @s remove mini_island_cage
tag @s remove mini_island_cageE
tag @s remove ancient_city_cage
tag @s remove ancient_city_cageE
tag @s remove default_cage
tag @s remove default_cageE


scoreboard players reset @s