# = intermission =
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 10..20 run titleraw @s actionbar {"rawtext":[{"text": "Game starts in §a"}, {"score": {"name": "timer_s", "objective": "lobby"}}, {"text": "§f Seconds."}]}
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 6..9 run titleraw @s actionbar {"rawtext":[{"text": "Game starts in §2"}, {"score": {"name": "timer_s", "objective": "lobby"}}, {"text": "§f Seconds."}]}
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 3..5 run titleraw @s actionbar {"rawtext":[{"text": "Game starts in §e"}, {"score": {"name": "timer_s", "objective": "lobby"}}, {"text": "§f Seconds.."}]}
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 2 run titleraw @s actionbar {"rawtext":[{"text": "Game starts in §6"}, {"score": {"name": "timer_s", "objective": "lobby"}}, {"text": "§f Seconds..."}]}
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 1 run titleraw @s actionbar {"rawtext":[{"text": "Game starts in §4§l"}, {"score": {"name": "timer_s", "objective": "lobby"}}, {"text": "§r§f Second!"}]}
# = game off =
execute as @a[tag=lobby] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score timer_s lobby matches 21 run titleraw @s actionbar {"rawtext":[{"text": "§4The game has been disabled by the host."}]}
# = standing on the spawn =
execute as @a[tag=lobby] at @s if entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] run titleraw @s actionbar {"rawtext":[{"text": "           Welcome to §b§lSky§awars!      \n"}, {"text": "§r§fJoin my :§5 discord.gg/GpwNShCz7m§r \n"}, {"text": "       A map by: §eBonnieRobloxRIP"}]}
# = game =
# // normal
execute as @a[tag=!spectator] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score game lobby matches 1 unless score started game matches 0 run titleraw @s actionbar {"rawtext":[{"text": "§a§l          "},{"score":{"name": "playercount", "objective": "game"}}, {"text": " §r§fPlayers left.\n"}, {"text": "§fTime Left: §b§l"}, {"score":{"name":"timer_m", "objective":"game"}}, {"text": " §r§fMinutes §b§l"}, {"score":{"name":"timer_s", "objective":"game"}}, {"text": " §r§fSeconds"}]}
execute as @a[tag=!spectator] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score game lobby matches 1 unless score started game matches 1 run titleraw @s actionbar {"rawtext":[{"text": "§fThe game is starting in: §b§l"}, {"score":{"name":"timer_s", "objective":"game"}}, {"text": " §r§fSeconds!"}]}
# // spectating
execute as @a[tag=spectator] at @s unless entity @s[x=0, y=1, z=-1, dx=0, dy=0, dz=0] if score game lobby matches 1 run titleraw @s actionbar {"rawtext":[{"text": "§o§7To stop spectating go to these coordinates 0 1 -1§r \n§a§l                   "},{"score":{"name": "playercount", "objective": "game"}}, {"text": " §r§fPlayers left.\n"}, {"text": "           §fTime Left: §b§l"}, {"score":{"name":"timer_m", "objective":"game"}}, {"text": " §r§fMinutes §b§l"}, {"score":{"name":"timer_s", "objective":"game"}}, {"text": " §r§fSeconds"}]}