# = SYSTEM RUN =
# - Open entrance door -
execute as @s[type=brr:flood_room, name=endless] at @s if score started endless matches 1 if score endless_timer_s endless matches 16 if score endless_timer_ms endless matches 1 run structure load "medium:MediumTunnelDoor2" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=endless] at @s if score started endless matches 1 if score endless_timer_s endless matches 16 if score endless_timer_ms endless matches 10 run structure load "medium:MediumTunnelDoor3" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=endless] at @s if score started endless matches 1 if score endless_timer_s endless matches 16 if score endless_timer_ms endless matches 10 run playsound sfx.doors.tunnelopen @a[tag=endless] ~1.5 ~3 ~8
# - Level title -
execute as @a[tag=endless] at @s if score endless_timer_s endless matches 16 if score endless_timer_ms endless matches 10 if score started endless matches 1 run title @a[tag=endless] subtitle §6Confusing Lines
execute as @a[tag=endless] at @s if score endless_timer_s endless matches 16 if score endless_timer_ms endless matches 10 if score started endless matches 1 run titleraw @a[tag=endless] title {"rawtext":[{"text": "§eROOM "}, {"score":{"name": "room_count", "objective": "endless"}}]}
execute as @a[tag=endless] at @s run tag @s add endless_music
# - Test for buttons -
# // Button 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players add R2B1a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 1 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.start @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 1 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-7
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 3 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-6
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 5 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 7 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 9 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 11 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 13 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 15 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 17 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 19 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 21 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 23 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 25 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^6
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run setblock ^-4 ^3 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run stopsound @a[tag=endless] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.stop @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 0 if score R2B1a endless matches 27.. if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R2B1 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B1 endless matches 1 if score R2B1a endless matches 27.. if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players reset R2B1a endless
# // Button 2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players add R2B2a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 1 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.start @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 1 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 3 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 5 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 7 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 9 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 11 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 13 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 15 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 17 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 19 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 21 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 23 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run setblock ^-6 ^6 ^-3 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run stopsound @a[tag=endless] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.stop @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 0 if score R2B2a endless matches 25.. if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R2B2 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B2 endless matches 1 if score R2B2a endless matches 25.. if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players reset R2B2a endless
# // Button 3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R2B3a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 1 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^5 ^4 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 4 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^6 ^4 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 7 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^7 ^4 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^8 ^4 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound sfx.moving_part.start @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^6 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 12 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^5 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 14 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^4 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 16 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^3 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 18 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^2 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 20 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^1 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 22 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^ 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 24 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-1 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 26 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-2 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 28 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-3 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 30 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-4 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 30 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^6 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 32 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-5 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 32 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^5 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 34 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-6 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 34 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^4 180_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock  ^ ^8 ^6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run stopsound @a[tag=endless] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound sfx.moving_part.stop @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 39 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^7 ^4 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 42 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^6 ^4 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 45 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^5 ^4 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 0 if score R2B3a endless matches 45.. if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R2B3 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B3 endless matches 1 if score R2B3a endless matches 45.. if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R2B3a endless
# // Button 4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players add R2B4a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 1 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^6 ^ air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 4 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^7 ^ air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 7 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^8 ^ air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 10 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^9 ^ air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^10 ^ air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run playsound sfx.moving_part.start @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-7
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-7
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 15 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-6
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 15 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-6
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 17 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 17 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 19 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 19 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 21 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 21 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 23 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 23 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 25 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 25 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 27 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 27 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 29 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 29 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 31 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 31 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^2
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 33 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 33 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^3
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 35 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 35 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^4
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^10 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^5 ^10 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run stopsound @a[tag=endless] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run playsound sfx.moving_part.stop @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 40 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^9 ^ iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 43 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^8 ^ iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 46 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^7 ^ iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 49 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^6 ^ iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 0 if score R2B4a endless matches 49.. if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players set R2B4 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B4 endless matches 1 if score R2B4a endless matches 49.. if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players reset R2B4a endless
# // Button 5
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players add R2B5a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 1 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^12 ^-2 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 4 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^13 ^-2 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 7 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^14 ^-2 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 10 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^15 ^-2 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^16 ^-2 air destroy
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run playsound sfx.moving_part.start @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^7 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 15 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^6 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 15 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 17 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 17 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 19 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 19 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 21 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 21 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 23 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 23 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^5 ^16 ^-1 ladder["facing_direction"=3]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^-4 ^16 ^-1 ladder["facing_direction"=3]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^6 ^15 ^-4 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^-6 ^16 ^-2 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run stopsound @a[tag=endless] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run playsound sfx.moving_part.stop @a[tag=endless]
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 42 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^15 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 45 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^14 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 48 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^13 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 51 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^12 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 0 if score R2B5a endless matches 51.. if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players set R2B5 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B5 endless matches 1 if score R2B5a endless matches 51.. if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players reset R2B5a endless
# // Exit Button
execute as @e[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 0 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R2B6a endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 0 if score R2B6a endless matches 1 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run fill ^-3 ^19 ^-7 ^-4 ^19 ^-7 air
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 0 if score R2B6a endless matches 10 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run fill ^-3 ^20 ^-7 ^-4 ^20 ^-7 air
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 0 if score R2B6a endless matches 10 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run tellraw @a[tag=endless] {"rawtext":[{"text": "§eTunnel Gate has been Opened!"}]}
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 0 if score R2B6a endless matches 10.. if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R2B6 endless 1
execute as @s[type=brr:flood_room, name=endless] at @s if score R2B6 endless matches 1 if score R2B6a endless matches 10.. if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R2B6a endless
# // - Flooding -
execute if score started endless matches 1 if score p_game endless matches 1.. if score endless_end endless matches 0 run scoreboard players add endless_timer_ms endless 1
execute if score endless_timer_ms endless matches 20.. run scoreboard players remove endless_timer_s endless 1
execute if score endless_timer_ms endless matches 20.. run scoreboard players set endless_timer_ms endless 0
execute if score endless_timer_s endless matches ..0 run scoreboard players add flood endless 1
# // flood part
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 3 if score endless_timer_ms endless matches 0 run playsound sfx.doors.opened @a[tag=endless] ~1.5 ~3 ~8 1 0.7
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 3 if score endless_timer_ms endless matches 0 run structure load "medium:MediumTunnelDoor2" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 3 if score endless_timer_ms endless matches 5 run structure load "medium:MediumTunnelDoor1" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 3 if score endless_timer_ms endless matches 5 run structure load "easy:NuhUh" ~1 ~2 ~9
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 0 run tellraw @a[tag=endless] {"rawtext":[{"text":"§3Water is rising!"}]}
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 1 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F1" ~-6 ~2 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 2 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F2" ~-6 ~3 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 3 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F3" ~-6 ~4 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 4 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F4" ~-6 ~5 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 5 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F5" ~-6 ~6 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 6 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F6" ~-6 ~7 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 7 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F7" ~-6 ~8 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 8 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F8" ~-6 ~9 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 9 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F9" ~-6 ~10 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 10 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F10" ~-6 ~11 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 11 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F11" ~-6 ~12 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 12 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F12" ~-6 ~13 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 13 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F13" ~-6 ~14 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 14 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F14" ~-6 ~15 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 15 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F15" ~-6 ~16 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 16 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F16" ~-6 ~17 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 17 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F17" ~-6 ~18 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=endless] at @s if score flood endless matches 18 if score endless_timer_s endless matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F18" ~-6 ~19 ~-6 0_degrees none block_by_block 1
# // flood end
execute if score endless_timer_s endless matches ..0 run scoreboard players set endless_timer_s endless 4
execute if score flood endless matches 18 if score endless_timer_ms endless matches 10 run scoreboard players set endless_end endless 1
# // exit tunnel
execute as @s[type=brr:flood_room, name=endless] at @s run tag @a[tag=endless, x=~-4, y=~19, z=~-14, dx=1, dy=1, dz=4] add endlesstunnel
execute as @s[type=brr:flood_room, name=endless] at @s run tag @a[tag=endless, x=~-4, y=~19, z=~-7, dx=1, dy=1, dz=0] remove endlesstunnel
# // exit player count
scoreboard players set p_tunnel endless 0
execute as @a[tag=endlesstunnel] at @s run scoreboard players add p_tunnel endless 1
# // transition into room 3
execute if score p_tunnel endless = p_game endless run scoreboard players set endless_end endless 1
execute if score endless_end endless matches 1 run scoreboard players add endless_transition endless 1
execute if score endless_transition endless matches 1 as @s[type=brr:flood_room, name=endless] at @s run playsound sfx.doors.opened @a[tag=endless] ~-3.5 ~19 ~-8 1 0.7
execute if score endless_transition endless matches 1 as @s[type=brr:flood_room, name=endless] at @s run structure load "medium:MediumTunnelDoor2" ~-4 ~19 ~-8
execute if score endless_transition endless matches 10 as @s[type=brr:flood_room, name=endless] at @s run structure load "medium:MediumTunnelDoor1" ~-4 ~19 ~-8
execute if score endless_transition endless matches 10 as @s[type=brr:flood_room, name=endless] at @s positioned ~ ~2 ~ run fill ~-6 ~ ~-6 ~6 ~19 ~6 water
execute if score endless_transition endless matches 31.. run function game_functions/mode_endless/reset_room