# = SYSTEM RUN =
# - Open entrance door -
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score started2 medium matches 1 if score r2_timer_s medium matches 16 if score r2_timer_ms medium matches 1 run structure load "medium:MediumTunnelDoor2" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score started2 medium matches 1 if score r2_timer_s medium matches 16 if score r2_timer_ms medium matches 10 run structure load "medium:MediumTunnelDoor3" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score started2 medium matches 1 if score r2_timer_s medium matches 16 if score r2_timer_ms medium matches 10 run playsound sfx.doors.tunnelopen @a[tag=medium] ~1.5 ~3 ~8
# - Level title -
execute as @a[tag=medium] at @s if score r2_timer_s medium matches 16 if score r2_timer_ms medium matches 10 if score started2 medium matches 1 run title @a[tag=medium] subtitle §6Confusing Lines
execute as @a[tag=medium] at @s if score r2_timer_s medium matches 16 if score r2_timer_ms medium matches 10 if score started2 medium matches 1 run title @a[tag=medium] title §eROOM 2
# - Test for buttons -
# // Button 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players add R2B1a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 1 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.start @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 1 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-7
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 3 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-6
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 5 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 7 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 9 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 11 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 13 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^-1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 15 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 17 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 19 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 21 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 23 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 25 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^3 ^6
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run setblock ^-4 ^3 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run stopsound @a[tag=medium] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 27 if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.stop @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 0 if score R2B1a medium matches 27.. if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R2B1 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B1 medium matches 1 if score R2B1a medium matches 27.. if block ^6 ^3 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players reset R2B1a medium
# // Button 2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players add R2B2a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 1 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.start @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 1 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 3 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 5 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 7 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 9 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 11 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 13 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 15 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 17 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 19 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 21 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 23 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^6 ^-3 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run setblock ^-6 ^6 ^-3 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run stopsound @a[tag=medium] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 25 if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run playsound sfx.moving_part.stop @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 0 if score R2B2a medium matches 25.. if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R2B2 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B2 medium matches 1 if score R2B2a medium matches 25.. if block ^6 ^7 ^ brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players reset R2B2a medium
# // Button 3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R2B3a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 1 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^5 ^4 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 4 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^6 ^4 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 7 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^7 ^4 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^8 ^4 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound sfx.moving_part.start @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 10 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^6 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 12 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^5 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 14 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^4 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 16 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^3 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 18 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^2 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 20 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^1 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 22 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^ 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 24 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-1 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 26 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-2 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 28 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-3 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 30 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-4 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 30 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^6 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 32 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-5 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 32 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^5 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 34 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^-6 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 34 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^8 ^4 180_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock  ^ ^8 ^6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run stopsound @a[tag=medium] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 36 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound sfx.moving_part.stop @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 39 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^7 ^4 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 42 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^6 ^4 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 45 if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^ ^5 ^4 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 0 if score R2B3a medium matches 45.. if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R2B3 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B3 medium matches 1 if score R2B3a medium matches 45.. if block ^-6 ^9 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R2B3a medium
# // Button 4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players add R2B4a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 1 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^6 ^ air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 4 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^7 ^ air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 7 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^8 ^ air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 10 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^9 ^ air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^10 ^ air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run playsound sfx.moving_part.start @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-7
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 13 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-7
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 15 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-6
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 15 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-6
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 17 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 17 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 19 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 19 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 21 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 21 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 23 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 23 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 25 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^-1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 25 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^-1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 27 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 27 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 29 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 29 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 31 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 31 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^2
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 33 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 33 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^3
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 35 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 35 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^4
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^10 ^5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^10 ^5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-4 ^10 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^4 ^10 ^-6 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run stopsound @a[tag=medium] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 37 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run playsound sfx.moving_part.stop @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 40 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^9 ^ iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 43 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^8 ^ iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 46 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^7 ^ iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 49 if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-5 ^6 ^ iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 0 if score R2B4a medium matches 49.. if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players set R2B4 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B4 medium matches 1 if score R2B4a medium matches 49.. if block ^ ^12 ^6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players reset R2B4a medium
# // Button 5
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players add R2B5a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 1 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^12 ^-2 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 4 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^13 ^-2 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 7 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^14 ^-2 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 10 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^15 ^-2 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^16 ^-2 air destroy
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run playsound sfx.moving_part.start @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^7 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 13 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 15 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^6 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 15 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 17 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 17 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 19 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 19 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 21 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 21 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 23 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 23 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^ ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 25 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-7 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 27 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-6 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 29 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 31 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-4 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^4 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 33 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-3 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-5 ^15 ^-4 90_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^5 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 35 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-2 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 37 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run structure load "medium/room2/1_confusing_lines:MMR2V1M1" ^-1 ^16 ^-2 270_degrees
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^6 ^15 ^-4 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^-6 ^16 ^-2 chiseled_stone_bricks
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run stopsound @a[tag=medium] sfx.moving_part.start
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 39 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run playsound sfx.moving_part.stop @a[tag=medium]
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 42 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^15 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 45 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^14 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 48 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^13 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 51 if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run setblock ^ ^12 ^-2 iron_chain
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 0 if score R2B5a medium matches 51.. if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players set R2B5 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B5 medium matches 1 if score R2B5a medium matches 51.. if block ^5 ^16 ^-6 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="south"] run scoreboard players reset R2B5a medium
# // Exit Button
execute as @e[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 0 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R2B6a medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 0 if score R2B6a medium matches 1 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run fill ^-3 ^19 ^-7 ^-4 ^19 ^-7 air
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 0 if score R2B6a medium matches 10 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run fill ^-3 ^20 ^-7 ^-4 ^20 ^-7 air
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 0 if score R2B6a medium matches 10 if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run tellraw @a[tag=medium] {"rawtext":[{"text": "§eTunnel Gate has been Opened!"}]}
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 0 if score R2B6a medium matches 10.. if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R2B6 medium 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score R2B6 medium matches 1 if score R2B6a medium matches 10.. if block ^-6 ^19 ^2 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R2B6a medium
# // - Flooding -
execute if score started2 medium matches 1 if score p_game medium matches 1.. if score r2_end medium matches 0 run scoreboard players add r2_timer_ms medium 1
execute if score r2_timer_ms medium matches 20.. run scoreboard players remove r2_timer_s medium 1
execute if score r2_timer_ms medium matches 20.. run scoreboard players set r2_timer_ms medium 0
execute if score r2_timer_s medium matches ..0 run scoreboard players add flood2 medium 1
# // flood part
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 3 if score r2_timer_ms medium matches 0 run playsound sfx.doors.opened @a[tag=medium] ~1.5 ~3 ~8 1 0.7
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 3 if score r2_timer_ms medium matches 0 run structure load "medium:MediumTunnelDoor2" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 3 if score r2_timer_ms medium matches 5 run structure load "medium:MediumTunnelDoor1" ~1 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 3 if score r2_timer_ms medium matches 5 run structure load "easy:NuhUh" ~1 ~2 ~9
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 0 run tellraw @a[tag=medium] {"rawtext":[{"text":"§3Water is rising!"}]}
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 1 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F1" ~-6 ~2 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 2 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F2" ~-6 ~3 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 3 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F3" ~-6 ~4 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 4 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F4" ~-6 ~5 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 5 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F5" ~-6 ~6 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 6 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F6" ~-6 ~7 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 7 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F7" ~-6 ~8 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 8 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F8" ~-6 ~9 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 9 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F9" ~-6 ~10 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 10 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F10" ~-6 ~11 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 11 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F11" ~-6 ~12 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 12 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F12" ~-6 ~13 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 13 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F13" ~-6 ~14 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 14 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F14" ~-6 ~15 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 15 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F15" ~-6 ~16 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 16 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F16" ~-6 ~17 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 17 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F17" ~-6 ~18 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room2] at @s if score flood2 medium matches 18 if score r2_timer_s medium matches 0 run structure load "medium/room2/1_confusing_lines:MMR2V1F18" ~-6 ~19 ~-6 0_degrees none block_by_block 1
# // flood end
execute if score r2_timer_s medium matches ..0 run scoreboard players set r2_timer_s medium 4
execute if score flood2 medium matches 18 if score r2_timer_ms medium matches 10 run scoreboard players set r2_end medium 1
# // exit tunnel
execute as @s[type=brr:flood_room, name=medium_room2] at @s run tag @a[tag=medium, x=~-4, y=~19, z=~-14, dx=1, dy=1, dz=4] add mediumtunnel2
execute as @s[type=brr:flood_room, name=medium_room2] at @s run tag @a[tag=medium, x=~-4, y=~19, z=~-7, dx=1, dy=1, dz=0] remove mediumtunnel2
# // exit player count
scoreboard players set p_tunnel2 medium 0
execute as @a[tag=mediumtunnel2] at @s run scoreboard players add p_tunnel2 medium 1
# // transition into room 3
execute if score p_tunnel2 medium = p_game medium if score started3 medium matches 0 run scoreboard players set r2_end medium 1
execute if score r2_end medium matches 1 run scoreboard players add r2_transition medium 1
execute if score r2_transition medium matches 1 as @s[type=brr:flood_room, name=medium_room2] at @s run playsound sfx.doors.opened @a[tag=medium] ~-3.5 ~19 ~-8 1 0.7
execute if score r2_transition medium matches 1 as @s[type=brr:flood_room, name=medium_room2] at @s run structure load "medium:MediumTunnelDoor2" ~-4 ~19 ~-8
execute if score r2_transition medium matches 10 as @s[type=brr:flood_room, name=medium_room2] at @s run structure load "medium:MediumTunnelDoor1" ~-4 ~19 ~-8
execute if score r2_transition medium matches 10 as @s[type=brr:flood_room, name=medium_room2] at @s positioned ~ ~2 ~ run fill ~-6 ~ ~-6 ~6 ~19 ~6 water
execute if score r2_transition medium matches 10 run scoreboard players set started3 medium 1
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B1 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B2 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B3 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B4 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B5 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset R2B6 medium
execute if score r2_transition medium matches 10.. run scoreboard players reset r2_timer_ms medium
execute if score r2_transition medium matches 10.. run scoreboard players reset r2_timer_s medium
execute if score r2_transition medium matches 10.. run scoreboard players reset r2_end medium
execute if score r2_transition medium matches 10.. run scoreboard players reset r2_transition medium