# = SYSTEM RUN =
# - Open entrance door -
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score started3 medium matches 1 if score r3_timer_s medium matches 16 if score r3_timer_ms medium matches 1 run structure load "medium:MediumTunnelDoor2" ~3 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score started3 medium matches 1 if score r3_timer_s medium matches 16 if score r3_timer_ms medium matches 10 run structure load "medium:MediumTunnelDoor3" ~3 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score started3 medium matches 1 if score r3_timer_s medium matches 16 if score r3_timer_ms medium matches 10 run playsound sfx.doors.tunnelopen @a[tag=medium] ~3.5 ~3 ~8
# - Level title -
execute as @a[tag=medium] at @s if score r3_timer_s medium matches 16 if score r3_timer_ms medium matches 10 if score started3 medium matches 1 run title @a[tag=medium] subtitle §6Labyrinth
execute as @a[tag=medium] at @s if score r3_timer_s medium matches 16 if score r3_timer_ms medium matches 10 if score started3 medium matches 1 run title @a[tag=medium] title §eROOM 3
# - Test for buttons -
# // Button 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R3B1a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if score R3B1a medium matches 1 if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound heavy_metal_door.open @a[tag=medium] ^2 ^3 ^-4.5
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if score R3B1a medium matches 1 if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M1" ^2 ^3 ^-5
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if score R3B1a medium matches 3 if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M1" ^2 ^2 ^-5
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if score R3B1a medium matches 5 if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M1" ^2 ^1 ^-5
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 0 if score R3B1a medium matches 5.. if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B1 medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B1 medium matches 1 if score R3B1a medium matches 5.. if block ^-6 ^3 ^3 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R3B1a medium
# // Button 2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R3B2a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if score R3B2a medium matches 1 if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run playsound heavy_metal_door.open @a[tag=medium] ^-3.5 ^10 ^
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if score R3B2a medium matches 1 if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M2" ^-5 ^6 ^2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if score R3B2a medium matches 3 if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M2" ^-5 ^7 ^2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if score R3B2a medium matches 5 if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M2" ^-5 ^8 ^2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 0 if score R3B2a medium matches 5.. if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B2 medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B2 medium matches 1 if score R3B2a medium matches 5.. if block ^-1 ^6 ^-2 brr:flood_button["brr:button_type"="parkour","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R3B2a medium
# // Button 3 on
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players add R3B3a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 1 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B5 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 1 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B4 medium 2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 1 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^ ^10 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 3 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^ ^11 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 5 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^ ^12 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 7 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^ ^13 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 10.. unless score R3B4 medium matches 0 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B4 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches 10.. if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B3 medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 1 if score R3B3a medium matches 10.. if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players reset R3B3a medium
# // Button 3 off // I hate mechanical buttons. this took 16 hours of blood, sweat and tears.
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players remove R3B3a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if score R3B3a medium matches -1 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^ ^13 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if score R3B3a medium matches -3 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^ ^12 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if score R3B3a medium matches -5 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^ ^11 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if score R3B3a medium matches -7 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^ ^10 ^4
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 2 if score R3B3a medium matches ..-9 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run scoreboard players set R3B3 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches ..-9 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"] run setblock ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="east"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B3 medium matches 0 if score R3B3a medium matches ..-9 if block ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="east"] run scoreboard players reset R3B3a medium
# // Button 4 on
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players add R3B4a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 1 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R3B5 medium 2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 1 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R3B3 medium 2
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 1 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^4 ^10 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 3 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^4 ^11 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 5 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3a" ^4 ^12 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 10.. unless score R3B3 medium matches 0 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R3B3 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches 10.. if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R3B4 medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 1 if score R3B4a medium matches 10.. if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players reset R3B4a medium
# // Button 4 off
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 2 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players remove R3B4a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 2 if score R3B4a medium matches -1 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^4 ^12 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 2 if score R3B4a medium matches -3 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^4 ^11 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 2 if score R3B4a medium matches -5 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run structure load "medium/room3/1_labyrinth:MMR3V1M3" ^4 ^10 ^3
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 2 if score R3B4a medium matches ..-9 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run scoreboard players set R3B4 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches ..-9 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"] run setblock ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="west"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B4 medium matches 0 if score R3B4a medium matches ..-9 if block ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="west"] run scoreboard players reset R3B4a medium
# // Button 5
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 0 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players add R3B5a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 2 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players add R3B5a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 2 if score R3B5a medium matches 1 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players set R3B3 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 2 if score R3B5a medium matches 1 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^-6 ^11 ^4 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="east"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 0 if score R3B5a medium matches 20.. if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="north"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 0 if score R3B5a medium matches 20.. if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="north"] run scoreboard players reset R3B5a medium
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 0 if score R3B5a medium matches 1 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players set R3B4 medium 0
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 0 if score R3B5a medium matches 1 if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^6 ^11 ^5 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="west"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 2 if score R3B5a medium matches 20.. if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=true, "minecraft:block_face"="north"] run setblock ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="north"]
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B5 medium matches 2 if score R3B5a medium matches 20.. if block ^2 ^16 ^6 brr:flood_button["brr:button_type"="mechanical","brr:pressed"=false, "minecraft:block_face"="north"] run scoreboard players reset R3B5a medium
# // Exit Button
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players add R3B6a medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if score R3B6a medium matches 1 if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run structure load "medium/room3/1_labyrinth:MMR3V1M4" ^ ^16 ^-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if score R3B6a medium matches 1 if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run fill ^-7 ^19 ^-4 ^-7 ^19 ^-5 air
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if score R3B6a medium matches 10 if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run fill ^-7 ^20 ^-4 ^-7 ^20 ^-5 air
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if score R3B6a medium matches 10 if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run tellraw @a[tag=medium] {"rawtext":[{"text": "§eTunnel Gate has been Opened!"}]}
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 0 if score R3B6a medium matches 10.. if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players set R3B6 medium 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score R3B6 medium matches 1 if score R3B6a medium matches 10.. if block ^6 ^20 ^6 brr:flood_button["brr:button_type"="exit","brr:pressed"=true, "minecraft:block_face"="north"] run scoreboard players reset R3B6a medium
# // - Flooding -
execute if score started3 medium matches 1 if score p_game medium matches 1.. if score r3_end medium matches 0 run scoreboard players add r3_timer_ms medium 1
execute if score r3_timer_ms medium matches 20.. run scoreboard players remove r3_timer_s medium 1
execute if score r3_timer_ms medium matches 20.. run scoreboard players set r3_timer_ms medium 0
execute if score r3_timer_s medium matches ..0 run scoreboard players add flood3 medium 1
# // flood part
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 3 if score r3_timer_ms medium matches 0 run playsound sfx.doors.opened @a[tag=medium] ~3.5 ~3 ~8 1 0.7
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 3 if score r3_timer_ms medium matches 0 run structure load "medium:MediumTunnelDoor2" ~3 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 3 if score r3_timer_ms medium matches 5 run structure load "medium:MediumTunnelDoor1" ~3 ~2 ~8
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 3 if score r3_timer_ms medium matches 5 run structure load "easy:NuhUh" ~3 ~2 ~9
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 0 run tellraw @a[tag=medium] {"rawtext":[{"text":"§3Water is rising!"}]}
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 1 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F1" ~-6 ~2 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 2 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F2" ~-6 ~3 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 3 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F3" ~-6 ~4 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 4 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F4" ~-6 ~5 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 5 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F5" ~-6 ~6 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 6 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F6" ~-6 ~7 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 7 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F7" ~-6 ~8 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 8 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F8" ~-6 ~9 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 9 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F9" ~-6 ~10 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 10 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F10" ~-6 ~11 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 11 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F11" ~-6 ~12 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 12 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F12" ~-6 ~13 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 13 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F13" ~-6 ~14 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 14 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F14" ~-6 ~15 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 15 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F15" ~-6 ~16 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 16 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F16" ~-6 ~17 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 17 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F17" ~-6 ~18 ~-6 0_degrees none block_by_block 1
execute as @s[type=brr:flood_room, name=medium_room3] at @s if score flood3 medium matches 18 if score r3_timer_s medium matches 0 run structure load "medium/room3/1_labyrinth:MMR3V1F18" ~-6 ~19 ~-6 0_degrees none block_by_block 1
# // flood end
execute if score r3_timer_s medium matches ..0 run scoreboard players set r3_timer_s medium 4
execute if score flood3 medium matches 18 if score r3_timer_ms medium matches 10 run scoreboard players set r3_end medium 1
# // exit tunnel
execute as @s[type=brr:flood_room, name=medium_room3] at @s run tag @a[tag=medium, x=~-15, y=~19, z=~-5, dx=5, dy=1, dz=1] add mediumtunnel3
execute as @s[type=brr:flood_room, name=medium_room3] at @s run tag @a[tag=medium, x=~-7, y=~19, z=~-5, dx=0, dy=1, dz=1] remove mediumtunnel3
# // exit player count
scoreboard players set p_tunnel3 medium 0
execute as @a[tag=mediumtunnel3] at @s run scoreboard players add p_tunnel3 medium 1
# // transition into room 3
execute if score p_tunnel3 medium = p_game medium if score started4 medium matches 0 run scoreboard players set r3_end medium 1
execute if score r3_end medium matches 1 run scoreboard players add r3_transition medium 1
execute if score r3_transition medium matches 1 as @s[type=brr:flood_room, name=medium_room3] at @s run playsound sfx.doors.opened @a[tag=medium] ~-8 ~19.5 ~-4.5 1 0.7
execute if score r3_transition medium matches 1 as @s[type=brr:flood_room, name=medium_room3] at @s run structure load "medium:MediumTunnelDoor2" ~-8 ~19 ~-5 270_degrees
execute if score r3_transition medium matches 10 as @s[type=brr:flood_room, name=medium_room3] at @s run structure load "medium:MediumTunnelDoor1" ~-8 ~19 ~-5 270_degrees
execute if score r3_transition medium matches 10 as @s[type=brr:flood_room, name=medium_room3] at @s positioned ~ ~2 ~ run fill ~-6 ~ ~-6 ~6 ~19 ~6 water
execute if score r3_transition medium matches 10 run scoreboard players set started4 medium 1
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B1 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B2 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B3 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B4 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B5 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset R3B6 medium
execute if score r3_transition medium matches 10.. run scoreboard players reset r3_timer_ms medium
execute if score r3_transition medium matches 10.. run scoreboard players reset r3_timer_s medium
execute if score r3_transition medium matches 10.. run scoreboard players reset r3_end medium
execute if score r3_transition medium matches 10.. run scoreboard players reset r3_transition medium