export const SHOP_CATEGORY_RULES = {
    armor: { maxEquipped: 1, purchaseAgain: false },
    swords: { maxEquipped: 1, purchaseAgain: false },
    pickaxes: { maxEquipped: 1, purchaseAgain: false },
    axes: { maxEquipped: 1, purchaseAgain: false },
    shovels: { maxEquipped: 1, purchaseAgain: false },
    spears: { maxEquipped: 1, purchaseAgain: false },
    potions: { maxEquipped: 2, purchaseAgain: true },
    equipments: { maxEquipped: 2, purchaseAgain: true },
    blocks: { maxEquipped: 1, purchaseAgain: true },
    vip: { maxEquipped: 1, purchaseAgain: true },
    megavip: { maxEquipped: 1, purchaseAgain: true },
    brrtech: { maxEquipped: 1, purchaseAgain: true },
    cages: { maxEquipped: 1, purchaseAgain: false },
    passes: { maxEquipped: 1, purchaseAgain: false }
};

export const SHOP_CATALOG = [
    {
        key: "wooden_sword",
        displayName: "Wooden Sword",
        signKeys: ["§f§lWooden Sword"],
        ownershipTag: "sword_wooden",
        requiresCoins: true,
        requiresWins: false,
        category: "swords",
        equipMessage: "§bEquipped §u§lGod Armor",
        equipMessage: "§bEquipped §fWooden Sword"
    },
    {
        key: "copper_sword",
        displayName: "Copper Sword",
        signKeys: ["§6§lCopper Sword"],
        ownershipTag: "sword_copper",
        requiresCoins: true,
        requiresWins: false,
        category: "swords",
        equipTag: "sword_copperE",
        equipMessage: "§bEquipped §6Copper Sword"
    },
    {
        key: "stone_sword",
        displayName: "Stone Sword",
        signKeys: ["§7§lStone Sword"],
        ownershipTag: "sword_stone",
        requiresCoins: true,
        requiresWins: false,
        category: "swords",
        equipTag: "sword_stoneE",
        equipMessage: "§bEquipped §7Stone Sword"
    },
    {
        key: "gold_sword",
        displayName: "Gold Sword",
        signKeys: ["§e§lGold Sword"],
        ownershipTag: "sword_gold",
        requiresCoins: true,
        requiresWins: false,
        category: "swords",
        equipTag: "sword_goldE",
        equipMessage: "§bEquipped §eGold Sword"
    },
    {
        key: "iron_sword",
        displayName: "Iron Sword",
        signKeys: ["§f§lIron Sword"],
        ownershipTag: "sword_iron",
        requiresCoins: true,
        requiresWins: false,
        category: "swords",
        equipTag: "sword_ironE",
        equipMessage: "§bEquipped §fIron Sword"
    },
    {
        key: "diamond_sword",
        displayName: "Diamond Sword",
        signKeys: ["§b§lDiamond Sword"],
        ownershipTag: "sword_diamond",
        requiresCoins: true,
        requiresWins: true,
        category: "swords",
        equipTag: "sword_diamondE",
        equipMessage: "§bEquipped §bDiamond Sword"
    },
    {
        key: "netherite_sword",
        displayName: "Netherite Sword",
        signKeys: ["§5§lNetherite Sword"],
        ownershipTag: "sword_netherite",
        requiresCoins: true,
        requiresWins: true,
        category: "swords",
        equipTag: "sword_netheriteE",
        equipMessage: "§bEquipped §5Netherite Sword"
    },
    {
        key: "wooden_pickaxe",
        displayName: "Wooden Pickaxe",
        signKeys: ["§f§lWooden Pickaxe"],
        ownershipTag: "pickaxe_wooden",
        requiresCoins: true,
        requiresWins: false,
        category: "pickaxes",
        equipTag: "pickaxe_woodenE",
        equipMessage: "§bEquipped §fWooden Pickaxe"
    },
    {
        key: "copper_pickaxe",
        displayName: "Copper Pickaxe",
        signKeys: ["§6§lCopper Pickaxe"],
        ownershipTag: "pickaxe_copper",
        requiresCoins: true,
        requiresWins: false,
        category: "pickaxes",
        equipTag: "pickaxe_copperE",
        equipMessage: "§bEquipped §6Copper Pickaxe"
    },
    {
        key: "stone_pickaxe",
        displayName: "Stone Pickaxe",
        signKeys: ["§7§lStone Pickaxe"],
        ownershipTag: "pickaxe_stone",
        requiresCoins: true,
        requiresWins: false,
        category: "pickaxes",
        equipTag: "pickaxe_stoneE",
        equipMessage: "§bEquipped §7Stone Pickaxe"
    },
    {
        key: "gold_pickaxe",
        displayName: "Gold Pickaxe",
        signKeys: ["§e§lGold Pickaxe"],
        ownershipTag: "pickaxe_gold",
        requiresCoins: true,
        requiresWins: false,
        category: "pickaxes",
        equipTag: "pickaxe_goldE",
        equipMessage: "§bEquipped §eGold Pickaxe"
    },
    {
        key: "iron_pickaxe",
        displayName: "Iron Pickaxe",
        signKeys: ["§f§lIron Pickaxe"],
        ownershipTag: "pickaxe_iron",
        requiresCoins: true,
        requiresWins: false,
        category: "pickaxes",
        equipTag: "pickaxe_ironE",
        equipMessage: "§bEquipped §fIron Pickaxe"
    },
    {
        key: "diamond_pickaxe",
        displayName: "Diamond Pickaxe",
        signKeys: ["§b§lDiamond Pickaxe"],
        ownershipTag: "pickaxe_diamond",
        requiresCoins: true,
        requiresWins: true,
        category: "pickaxes",
        equipTag: "pickaxe_diamondE",
        equipMessage: "§bEquipped §bDiamond Pickaxe"
    },
    {
        key: "netherite_pickaxe",
        displayName: "Netherite Pickaxe",
        signKeys: ["§5§lNetherite Pickaxe"],
        ownershipTag: "pickaxe_netherite",
        requiresCoins: true,
        requiresWins: true,
        category: "pickaxes",
        equipTag: "pickaxe_netheriteE",
        equipMessage: "§bEquipped §5Netherite Pickaxe"
    },
    {
        key: "wooden_axe",
        displayName: "Wooden Axe",
        signKeys: ["§f§lWooden Axe"],
        ownershipTag: "axe_wooden",
        requiresCoins: true,
        requiresWins: false,
        category: "axes",
        equipTag: "axe_woodenE",
        equipMessage: "§bEquipped §fWooden Axe"
    },
    {
        key: "copper_axe",
        displayName: "Copper Axe",
        signKeys: ["§6§lCopper Axe"],
        ownershipTag: "axe_copper",
        requiresCoins: true,
        requiresWins: false,
        category: "axes",
        equipTag: "axe_copperE",
        equipMessage: "§bEquipped §6Copper Axe"
    },
    {
        key: "stone_axe",
        displayName: "Stone Axe",
        signKeys: ["§7§lStone Axe"],
        ownershipTag: "axe_stone",
        requiresCoins: true,
        requiresWins: false,
        category: "axes",
        equipTag: "axe_stoneE",
        equipMessage: "§bEquipped §7Stone Axe"
    },
    {
        key: "gold_axe",
        displayName: "Gold Axe",
        signKeys: ["§e§lGold Axe"],
        ownershipTag: "axe_gold",
        requiresCoins: true,
        requiresWins: false,
        category: "axes",
        equipTag: "axe_goldE",
        equipMessage: "§bEquipped §eGold Axe"
    },
    {
        key: "iron_axe",
        displayName: "Iron Axe",
        signKeys: ["§f§lIron Axe"],
        ownershipTag: "axe_iron",
        requiresCoins: true,
        requiresWins: false,
        category: "axes",
        equipTag: "axe_ironE",
        equipMessage: "§bEquipped §fIron Axe"
    },
    {
        key: "diamond_axe",
        displayName: "Diamond Axe",
        signKeys: ["§b§lDiamond Axe"],
        ownershipTag: "axe_diamond",
        requiresCoins: true,
        requiresWins: true,
        category: "axes",
        equipTag: "axe_diamondE",
        equipMessage: "§bEquipped §bDiamond Axe"
    },
    {
        key: "netherite_axe",
        displayName: "Netherite Axe",
        signKeys: ["§5§lNetherite Axe"],
        ownershipTag: "axe_netherite",
        requiresCoins: true,
        requiresWins: true,
        category: "axes",
        equipTag: "axe_netheriteE",
        equipMessage: "§bEquipped §5Netherite Axe"
    },
    {
        key: "wooden_shovel",
        displayName: "Wooden Shovel",
        signKeys: ["§f§lWooden Shovel"],
        ownershipTag: "shovel_wooden",
        requiresCoins: true,
        requiresWins: false,
        category: "shovels",
        equipTag: "shovel_woodenE",
        equipMessage: "§bEquipped §fWooden Shovel"
    },
    {
        key: "copper_shovel",
        displayName: "Copper Shovel",
        signKeys: ["§6§lCopper Shovel"],
        ownershipTag: "shovel_copper",
        requiresCoins: true,
        requiresWins: false,
        category: "shovels",
        equipTag: "shovel_copperE",
        equipMessage: "§bEquipped §6Copper Shovel"
    },
    {
        key: "stone_shovel",
        displayName: "Stone Shovel",
        signKeys: ["§7§lStone Shovel"],
        ownershipTag: "shovel_stone",
        requiresCoins: true,
        requiresWins: false,
        category: "shovels",
        equipTag: "shovel_stoneE",
        equipMessage: "§bEquipped §7Stone Shovel"
    },
    {
        key: "gold_shovel",
        displayName: "Gold Shovel",
        signKeys: ["§e§lGold Shovel"],
        ownershipTag: "shovel_gold",
        requiresCoins: true,
        requiresWins: false,
        category: "shovels",
        equipTag: "shovel_goldE",
        equipMessage: "§bEquipped §eGold Shovel"
    },
    {
        key: "iron_shovel",
        displayName: "Iron Shovel",
        signKeys: ["§f§lIron Shovel"],
        ownershipTag: "shovel_iron",
        requiresCoins: true,
        requiresWins: false,
        category: "shovels",
        equipTag: "shovel_ironE",
        equipMessage: "§bEquipped §fIron Shovel"
    },
    {
        key: "diamond_shovel",
        displayName: "Diamond Shovel",
        signKeys: ["§b§lDiamond Shovel"],
        ownershipTag: "shovel_diamond",
        requiresCoins: true,
        requiresWins: true,
        category: "shovels",
        equipTag: "shovel_diamondE",
        equipMessage: "§bEquipped §bDiamond Shovel"
    },
    {
        key: "netherite_shovel",
        displayName: "Netherite Shovel",
        signKeys: ["§5§lNetherite Shovel"],
        ownershipTag: "shovel_netherite",
        requiresCoins: true,
        requiresWins: true,
        category: "shovels",
        equipTag: "shovel_netheriteE",
        equipMessage: "§bEquipped §5Netherite Shovel"
    },
    {
        key: "leather_armor",
        displayName: "Leather Armor",
        signKeys: ["Leather Armor"],
        ownershipTag: "armor_leather",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_leatherE",
        equipMessage: "§bEquipped §fLeather Armor"
    },
    {
        key: "copper_armor",
        displayName: "Copper Armor",
        signKeys: ["§6§lCopper Armor"],
        ownershipTag: "armor_copper",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_copperE",
        equipMessage: "§bEquipped §6Copper Armor"
    },
    {
        key: "chainmail_armor",
        displayName: "Chainmail Armor",
        signKeys: ["§7§lChainmail Armor"],
        ownershipTag: "armor_chainmail",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_chainmailE",
        equipMessage: "§bEquipped §7Chainmail Armor"
    },
    {
        key: "gold_armor",
        displayName: "Gold Armor",
        signKeys: ["§e§lGold Armor"],
        ownershipTag: "armor_gold",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_goldE",
        equipMessage: "§bEquipped §eGold Armor"
    },
    {
        key: "iron_armor",
        displayName: "Iron Armor",
        signKeys: ["§f§lIron Armor"],
        ownershipTag: "armor_iron",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_ironE",
        equipMessage: "§bEquipped §fIron Armor"
    },
    {
        key: "diamond_armor",
        displayName: "Diamond Armor",
        signKeys: ["§b§lDiamond Armor"],
        ownershipTag: "armor_diamond",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_diamondE",
        equipMessage: "§bEquipped §bDiamond Armor"
    },
    {
        key: "netherite_armor",
        displayName: "Netherite Armor",
        signKeys: ["§u§lNetherite Armor"],
        ownershipTag: "armor_netherite",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_netheriteE",
        equipMessage: "§bEquipped §uNetherite Armor"
    },
    {
        key: "crystal_armor",
        displayName: "Crystal Armor",
        signKeys: ["§d§lCrystal Armor"],
        ownershipTag: "armor_crystal",
        requiresCoins: false,
        requiresWins: true,
        category: "armor",
        equipTag: "armor_crystalE",
        equipMessage: "§bEquipped §d§lCrystal Armor"
    },
    {
        key: "speed_potion",
        displayName: "Speed Potion",
        signKeys: ["§b§lSpeed Potion"],
        ownershipTag: "potion_speed",
        requiresCoins: true,
        requiresWins: false,
        category: "potions",
        equipTag: "potion_speedE",
        equipMessage: "§bEquipped §b§lSpeed Potion"
    },
    {
        key: "jump_potion",
        displayName: "Jump Potion",
        signKeys: ["§a§lJump Potion"],
        ownershipTag: "potion_jump",
        requiresCoins: true,
        requiresWins: false,
        category: "potions",
        equipTag: "potion_jumpE",
        equipMessage: "§bEquipped §a§lJump Potion"
    },
    {
        key: "strength_potion",
        displayName: "Strength Potion",
        signKeys: ["§6§lStrength Potion"],
        ownershipTag: "potion_strength",
        requiresCoins: true,
        requiresWins: false,
        category: "potions",
        equipTag: "potion_strengthE",
        equipMessage: "§bEquipped §6§lStrength Potion"
    },
    {
        key: "health_potion",
        displayName: "Health Potion",
        signKeys: ["§c§lHealth Potion"],
        ownershipTag: "potion_health",
        requiresCoins: true,
        requiresWins: false,
        category: "potions",
        equipTag: "potion_healthE",
        equipMessage: "§bEquipped §c§lHealth Potion"
    },
    {
        key: "damage_potion",
        displayName: "Damage Potion",
        signKeys: ["§4§lDamage Potion"],
        ownershipTag: "potion_damage",
        requiresCoins: true,
        requiresWins: false,
        category: "potions",
        equipTag: "potion_damageE",
        equipMessage: "§bEquipped §4§lDamage Potion"
    },
    {
        key: "poison_potion",
        displayName: "Poison Potion",
        signKeys: ["§2§lPoison Potion"],
        ownershipTag: "potion_poison",
        requiresCoins: true,
        requiresWins: true,
        category: "potions",
        equipTag: "potion_poisonE",
        equipMessage: "§bEquipped §2§lPoison Potion"
    },
    {
        key: "wither_potion",
        displayName: "Wither Potion",
        signKeys: ["§8§lWither Potion"],
        ownershipTag: "potion_wither",
        requiresCoins: true,
        requiresWins: true,
        category: "potions",
        equipTag: "potion_witherE",
        equipMessage: "§bEquipped §8§lWither Potion"
    },
    {
        key: "regeneration_potion",
        displayName: "Regeneration Potion",
        signKeys: ["§d§lRegeneration Potion"],
        ownershipTag: "potion_regeneration",
        requiresCoins: true,
        requiresWins: true,
        category: "potions",
        equipTag: "potion_regenerationE",
        equipMessage: "§bEquipped §d§lRegeneration Potion"
    },
    {
        key: "turtlemaster_potion",
        displayName: "Turlemaster Potion",
        signKeys: ["§u§lTurtlemaster Potion"],
        ownershipTag: "potion_turtlemaster",
        requiresCoins: true,
        requiresWins: true,
        category: "potions",
        equipTag: "potion_turtlemasterE",
        equipMessage: "§bEquipped §u§lTurtlemaster Potion"
    },
    {
        key: "wooden_spear",
        displayName: "Wooden Spear",
        signKeys: ["§f§lWooden Spear"],
        ownershipTag: "spear_wooden",
        requiresCoins: true,
        requiresWins: false,
        category: "spears",
        equipTag: "spear_woodenE",
        equipMessage: "§bEquipped §fWooden Spear"
    },
    {
        key: "copper_spear",
        displayName: "Copper Spear",
        signKeys: ["§6§lCopper Spear"],
        ownershipTag: "spear_copper",
        requiresCoins: true,
        requiresWins: false,
        category: "spears",
        equipTag: "spear_copperE",
        equipMessage: "§bEquipped §6Copper Spear"
    },
    {
        key: "stone_spear",
        displayName: "Stone Spear",
        signKeys: ["§7§lStone Spear"],
        ownershipTag: "spear_stone",
        requiresCoins: true,
        requiresWins: false,
        category: "spears",
        equipTag: "spear_stoneE",
        equipMessage: "§bEquipped §7Stone Spear"
    },
    {
        key: "gold_spear",
        displayName: "Gold Spear",
        signKeys: ["§e§lGold Spear"],
        ownershipTag: "spear_gold",
        requiresCoins: true,
        requiresWins: false,
        category: "spears",
        equipTag: "spear_goldE",
        equipMessage: "§bEquipped §eGold Spear"
    },
    {
        key: "iron_spear",
        displayName: "Iron Spear",
        signKeys: ["§f§lIron Spear"],
        ownershipTag: "spear_iron",
        requiresCoins: true,
        requiresWins: false,
        category: "spears",
        equipTag: "spear_ironE",
        equipMessage: "§bEquipped §fIron Spear"
    },
    {
        key: "diamond_spear",
        displayName: "Diamond Spear",
        signKeys: ["§b§lDiamond Spear"],
        ownershipTag: "spear_diamond",
        requiresCoins: true,
        requiresWins: true,
        category: "spears",
        equipTag: "spear_diamondE",
        equipMessage: "§bEquipped §bDiamond Spear"
    },
    {
        key: "netherite_spear",
        displayName: "Netherite Spear",
        signKeys: ["§5§lNetherite Spear"],
        ownershipTag: "spear_netherite",
        requiresCoins: true,
        requiresWins: true,
        category: "spears",
        equipTag: "spear_netheriteE",
        equipMessage: "§bEquipped §5Netherite Spear"
    },
    {
        key: "grass_block",
        displayName: "Grass Block",
        signKeys: ["§2§lGrass x16"],
        ownershipTag: "block_grass",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_grassE",
        equipMessage: "§bEquipped §2§lGrass Blocks"
    },
    {
        key: "glass_block",
        displayName: "Glass Block",
        signKeys: ["§f§lGlass x16"],
        ownershipTag: "block_glass",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_glassE",
        equipMessage: "§bEquipped §f§lGlass Blocks"
    },
    {
        key: "planks_block",
        displayName: "Planks Block",
        signKeys: ["§lPlanks x16"],
        ownershipTag: "block_planks",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_planksE",
        equipMessage: "§bEquipped §f§lPlanks Blocks"
    },
    {
        key: "dev_block",
        displayName: "Dev Block",
        signKeys: ["§6§lDev x16"],
        ownershipTag: "block_dev",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_devE",
        equipMessage: "§bEquipped §6§lDev Blocks"
    },
    {
        key: "leaves_block",
        displayName: "Leaves Block",
        signKeys: ["§2§lLeaves x16"],
        ownershipTag: "block_leaves",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_leavesE",
        equipMessage: "§bEquipped §2§lLeaves Blocks"
    },
    {
        key: "cobblestone_block",
        displayName: "Cobblestone Block",
        signKeys: ["§7§lCobblestone x16"],
        ownershipTag: "block_cobblestone",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_cobblestoneE",
        equipMessage: "§bEquipped §7§lCobblestone Blocks"
    },
    {
        key: "wool_block",
        displayName: "Wool Block",
        signKeys: ["§f§lWool x16"],
        ownershipTag: "block_wool",
        requiresCoins: true,
        requiresWins: false,
        category: "blocks",
        equipTag: "block_woolE",
        equipMessage: "§bEquipped §f§lWool Blocks"
    },
    {
        key: "obsidian_block",
        displayName: "Obsidian Block",
        signKeys: ["§8§lObsidian x16"],
        ownershipTag: "block_obsidian",
        requiresCoins: true,
        requiresWins: true,
        category: "blocks",
        equipTag: "block_obsidianE",
        equipMessage: "§bEquipped §8§lObsidian Blocks"
    },
    {
        key: "bow",
        displayName: "Bow",
        signKeys: ["§7§lBow"],
        ownershipTag: "equipment_bow",
        requiresCoins: true,
        requiresWins: true,
        category: "equipments",
        equipTag: "equipment_bowE",
        equipMessage: "§bEquipped §7§lBow"
    },
    {
        key: "shield",
        displayName: "Shield",
        signKeys: ["§7§lShield"],
        ownershipTag: "equipment_shield",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_shieldE",
        equipMessage: "§bEquipped §7§lShield"
    },
    {
        key: "totem",
        displayName: "Totem",
        signKeys: ["§g§lTotem of undying"],
        ownershipTag: "equipment_totem",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_totemE",
        equipMessage: "§bEquipped §g§lTotem"
    },
    {
        key: "snowball",
        displayName: "Snowball",
        signKeys: ["§f§lSnowball x10"],
        ownershipTag: "equipment_snowball",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_snowballE",
        equipMessage: "§bEquipped §f§lSnowball"
    },
    {
        key: "milk",
        displayName: "Milk",
        signKeys: ["§f§lMilk Bucket"],
        ownershipTag: "equipment_milk",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_milkE",
        equipMessage: "§bEquipped §f§lMilk"
    },
    {
        key: "flint_and_steel",
        displayName: "Flint and Steel",
        signKeys: ["§8§lFlint and Steel"],
        ownershipTag: "equipment_flint_and_steel",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_flint_and_steelE",
        equipMessage: "§bEquipped §8§lFlint and Steel"
    },
    {
        key: "shears",
        displayName: "Shears",
        signKeys: ["§f§lShears"],
        ownershipTag: "equipment_shears",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_shearsE",
        equipMessage: "§bEquipped §f§lShears"
    },
    {
        key: "furnace",
        displayName: "Furnace",
        signKeys: ["§7§lFurnace"],
        ownershipTag: "equipment_furnace",
        requiresCoins: true,
        requiresWins: false,
        category: "equipments",
        equipTag: "equipment_furnaceE",
        equipMessage: "§bEquipped §7§lFurnace"
    },
    {
        key: "enchanted_gold_pickaxe",
        displayName: "Enchanted Gold Pickaxe",
        signKeys: ["§d§lEnchanted Gold Pickaxe"],
        ownershipTag: "vip_enchanted_gold_pickaxe",
        requiresCoins: false,
        requiresWins: false,
        requiresVip: true,
        category: "pickaxes",
        equipTag: "vip_enchanted_gold_pickaxeE",
        equipMessage: "§bEquipped §d§lEnchanted Gold Pickaxe"
    },
    {
        key: "enchanted_gold_armor",
        displayName: "Enchanted Gold Armor",
        signKeys: ["§d§lEnchanted Gold Armor"],
        ownershipTag: "vip_enchanted_gold_armor",
        requiresCoins: false,
        requiresWins: false,
        requiresVip: true,
        category: "armor",
        equipTag: "vip_enchanted_gold_armorE",
        equipMessage: "§bEquipped §d§lEnchanted Gold Armor"
    },
    {
        key: "ender_pearl",
        displayName: "Ender Pearl",
        signKeys: ["§9§lEnder Pearl"],
        ownershipTag: "vip_ender_pearl",
        requiresVip: true,
        requiresMegaVip: false,
        requiresCoins: true,
        requiresWins: true,
        category: "vip",
        equipTag: "vip_ender_pearlE",
        equipMessage: "§bEquipped §9§lEnder Pearl"
    },
    {
        key: "wind_charge",
        displayName: "Wind Charge",
        signKeys: ["§9§lWind Charge"],
        ownershipTag: "vip_wind_charge",
        requiresVip: true,
        requiresMegaVip: false,
        requiresCoins: true,
        requiresWins: true,
        category: "vip",
        equipTag: "vip_wind_chargeE",
        equipMessage: "§bEquipped §9§lWind Charge"
    },
    {
        key: "golden_apple",
        displayName: "Golden Apple",
        signKeys: ["§6§lGolden Apple"],
        ownershipTag: "vip_golden_apple",
        requiresVip: true,
        requiresMegaVip: false,
        requiresCoins: true,
        requiresWins: false,
        category: "vip",
        equipTag: "vip_golden_appleE",
        equipMessage: "§bEquipped §6§lGolden Apple"
    },
    {
        key: "enchanted_golden_apple",
        displayName: "Enchanted Golden Apple",
        signKeys: ["§d§lEnchanted Golden Apple"],
        ownershipTag: "vip_enchanted_golden_apple",
        requiresVip: true,
        requiresMegaVip: false,
        requiresCoins: true,
        requiresWins: true,
        category: "vip",
        equipTag: "vip_enchanted_golden_appleE",
        equipMessage: "§bEquipped §d§lEnchanted Golden Apple"
    },
    {
        key: "rgb_blocks",
        displayName: "RGB Blocks",
        signKeys: ["§4§lR§2G§bB §fBlocks"],
        ownershipTag: "vip_rgb_blocks",
        requiresCoins: false,
        requiresWins: false,
        requiresVip: true,
        category: "blocks",
        equipTag: "vip_rgb_blocksE",
        equipMessage: "§bEquipped §4§lR§2G§bB §fBlocks"
    },
    {
        key: "god_armor",
        displayName: "God Armor",
        signKeys: ["§u§lGod Armor"],
        ownershipTag: "megavip_god_armor",
        requiresCoins: false,
        requiresWins: true,
        requiresVip: true,
        requiresMegaVip: true,
        category: "armor",
        equipTag: "megavip_god_armorE",
        equipMessage: "§bEquipped §u§lGod Armor",
        announcementMessage: "§b{player} §uHas purchased the §u§o§lGod Armor.. We are dooomed"
    },
    {
        key: "trident",
        displayName: "Trident",
        signKeys: ["§u§lTrident"],
        ownershipTag: "megavip_trident",
        requiresCoins: true,
        requiresWins: true,
        requiresVip: true,
        requiresMegaVip: true,
        category: "equipments",
        equipTag: "megavip_tridentE",
        equipMessage: "§bEquipped §u§lTrident"
    },
    {
        key: "elytra",
        displayName: "Elytra",
        signKeys: ["§u§lElytra"],
        ownershipTag: "megavip_elytra",
        requiresCoins: false,
        requiresWins: false,
        requiresVip: true,
        requiresMegaVip: true,
        category: "megavip",
        equipTag: "megavip_elytraE",
        equipMessage: "§bEquipped §u§lElytra"
    },
    {
        key: "mace",
        displayName: "Mace",
        signKeys: ["§u§lMace"],
        ownershipTag: "megavip_mace",
        requiresCoins: true,
        requiresWins: true,
        requiresVip: true,
        requiresMegaVip: true,
        category: "equipments",
        equipTag: "megavip_maceE",
        equipMessage: "§bEquipped §u§lMace",
        announcementMessage: "§b{player} §uHas purchased the §u§o§lMace.. the end is near"
    },
    {
        key: "invisibility_potion",
        displayName: "Invisibility Potion",
        signKeys: ["§u§lInvisibility Potion"],
        ownershipTag: "potion_invisibility",
        requiresCoins: true,
        requiresWins: true,
        requiresVip: true,
        requiresMegaVip: true,
        category: "potions",
        equipTag: "potion_invisibilityE",
        equipMessage: "§bEquipped §u§lInvisibility Potion"
    },
    {
        key: "gluon_gun",
        displayName: "Gluon Gun",
        signKeys: ["§g§o§lGluon Gun"],
        ownershipTag: "megavip_gluon_gun",
        requiresCoins: true,
        requiresWins: true,
        category: "brrtech",
        equipTag: "megavip_gluon_gunE",
        equipMessage: "§bEquipped §g§o§lGluon Gun"
    },
    {
        key: "tau_cannon",
        displayName: "Tau Cannon",
        signKeys: ["§g§o§lTau Cannon"],
        ownershipTag: "megavip_tau_cannon",
        requiresCoins: true,
        requiresWins: true,
        category: "brrtech",
        equipTag: "megavip_tau_cannonE",
        equipMessage: "§bEquipped §g§o§lTau Cannon"
    },
    {
        key: "hive_hand",
        displayName: "Hive Hand",
        signKeys: ["§g§o§lHive Hand"],
        ownershipTag: "megavip_hive_hand",
        requiresCoins: true,
        requiresWins: true,
        category: "brrtech",
        equipTag: "megavip_hive_handE",
        equipMessage: "§bEquipped §g§o§lHive Hand"
    },
    {
        key: "glock17",
        displayName: "Glock 17",
        signKeys: ["§g§o§lGlock 17"],
        ownershipTag: "brr_glock17",
        requiresCoins: true,
        requiresWins: true,
        category: "brrtech",
        equipTag: "brr_glock17E",
        equipMessage: "§bEquipped §g§o§lGlock 17"
    },
    {
        key: "crowbar",
        displayName: "Crowbar",
        signKeys: ["§g§o§lCrowbar"],
        ownershipTag: "brr_crowbar",
        requiresCoins: true,
        requiresWins: true,
        category: "brrtech",
        equipTag: "brr_crowbarE",
        equipMessage: "§bEquipped §g§o§lCrowbar"
    },
    {
        key: "vip",
        displayName: "§e§l§oV.§gI.§6P.",
        signKeys: ["§e§l§oV.§gI.§6P."],
        ownershipTag: "vip",
        requiresCoins: true,
        requiresWins: true,
        category: "passes",
        announcementMessage: "§b{player} §eIs now a §e§l§oV.§gI.§6P.",
    },
    {
        key: "mega_vip",
        displayName: "§l§o§aM§2E§sG§bA §sV.§2I.§aP.",
        signKeys: ["§l§o§aM§2E§sG§bA §sV.§2I.§aP."],
        ownershipTag: "mega_vip",
        requiresCoins: true,
        requiresWins: true,
        category: "passes",
        announcementMessage: "§b{player} §uIs now a §l§o§aM§2E§sG§bA §sV.§2I.§aP.",
    },
    {
        key: "default_cage",
        displayName: "Default Cage",
        signKeys: ["§f§lDefault Cage"],
        ownershipTag: "default_cage",
        requiresCoins: false,
        requiresWins: false,
        category: "cages",
        equipTag: "default_cageE",
        equipMessage: "§bEquipped §f§lDefault Cage"
    },
    {
        key: "purple_cage",
        displayName: "Purple Cage",
        signKeys: ["§5§lPurple Cage"],
        ownershipTag: "purple_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "purple_cageE",
        equipMessage: "§bEquipped §5§lPurple Cage"
    },
    {
        key: "fire_cage",
        displayName: "Fire Cage",
        signKeys: ["§6§lFire Cage"],
        ownershipTag: "fire_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "fire_cageE",
        equipMessage: "§bEquipped §6§lFire Cage"
    },
    {
        key: "dev_cage",
        displayName: "Dev Cage",
        signKeys: ["§6§o§lDev Cage"],
        ownershipTag: "dev_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "dev_cageE",
        equipMessage: "§bEquipped §6§o§lDev Cage"
    },
    {
        key: "nether_cage",
        displayName: "Nether Cage",
        signKeys: ["§4§lNether Cage"],
        ownershipTag: "nether_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "nether_cageE",
        equipMessage: "§bEquipped §4§lNether Cage"
    },
    {
        key: "fish_tank_cage",
        displayName: "Fish Tank Cage",
        signKeys: ["§b§lFish Tank Cage"],
        ownershipTag: "fish_tank_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "fish_tank_cageE",
        equipMessage: "§bEquipped §b§lFish Tank Cage"
    },
    {
        key: "amethyst_cage",
        displayName: "Amethyst Cage",
        signKeys: ["§u§lAmethyst Cage"],
        ownershipTag: "amethyst_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "amethyst_cageE",
        equipMessage: "§bEquipped §u§lAmethyst Cage"
    },
    {
        key: "cherry_blossom_cage",
        displayName: "Cherry Blossom Cage",
        signKeys: ["§d§lCherry Blossom Cage"],
        ownershipTag: "cherry_blossom_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "cherry_blossom_cageE",
        equipMessage: "§bEquipped §d§lCherry Blossom Cage"
    },
    {
        key: "mini_island_cage",
        displayName: "Mini Island Cage",
        signKeys: ["§a§lMini Island Cage"],
        ownershipTag: "mini_island_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "mini_island_cageE",
        equipMessage: "§bEquipped §a§lMini Island Cage"
    },
    {
        key: "ancient_city_cage",
        displayName: "Ancient City Cage",
        signKeys: ["§9§lAncient City Cage"],
        ownershipTag: "ancient_city_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "ancient_city_cageE",
        equipMessage: "§bEquipped §9§lAncient City Cage"
    },
    {
        key: "diamond_sword_cage",
        displayName: "Diamond Sword Cage",
        signKeys: ["§b§lDiamond Sword Cage"],
        ownershipTag: "diamond_sword_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "diamond_sword_cageE",
        equipMessage: "§bEquipped §b§lDiamond Sword Cage"
    },
    {
        key: "copper_airship_cage",
        displayName: "Copper Airship Cage",
        signKeys: ["§6§lCopper Airship Cage"],
        ownershipTag: "copper_airship_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "copper_airship_cageE",
        equipMessage: "§bEquipped §6§lCopper Airship Cage"
    },
    {
        key: "bassalting_floater_cage",
        displayName: "Bassalting Floater Cage",
        signKeys: ["§8§lBassalting Floater Cage"],
        ownershipTag: "bassalting_floater_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "bassalting_floater_cageE",
        equipMessage: "§bEquipped §8§lBassalting Floater Cage"
    },
    {
        key: "azalea_tree_cage",
        displayName: "Azalea tree Cage",
        signKeys: ["§3§lAzalea tree Cage"],
        ownershipTag: "azalea_tree_cage",
        requiresCoins: true,
        requiresWins: true,
        category: "cages",
        equipTag: "azalea_tree_cageE",
        equipMessage: "§bEquipped §3§lAzalea tree Cage"
    },
    {
        key: "candy_land_cage",
        displayName: "Candy Land Cage",
        signKeys: ["§c§lCandy Land Cage"],
        ownershipTag: "candy_land_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "candy_land_cageE",
        equipMessage: "§bEquipped §c§lCandy Land Cage"
    },
    {
        key: "eaten_cage",
        displayName: "Eaten Cage",
        signKeys: ["§f§lEaten Cage"],
        ownershipTag: "eaten_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "eaten_cageE",
        equipMessage: "§bEquipped §f§lEaten Cage"
    },
    {
        key: "spruce_tree",
        displayName: "Spruce Tree Cage",
        signKeys: ["§f§lSpruce Tree Cage"],
        ownershipTag: "spruce_tree",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "spruce_treeE",
        equipMessage: "§bEquipped §f§lSpruce Tree Cage"
    },
    {
        key: "bamboo_forest",
        displayName: "Bamboo Forest Cage",
        signKeys: ["§a§lBamboo Forest Cage"],
        ownershipTag: "bamboo_forest",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "bamboo_forestE",
        equipMessage: "§bEquipped §a§lBamboo Forest Cage"
    },
    {
        key: "spawn_cage",
        displayName: "The Litteral Spawn Cage",
        signKeys: ["§f§lThe Litteral Spawn Cage"],
        ownershipTag: "spawn_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "spawn_cageE",
        equipMessage: "§bEquipped §f§lThe Litteral Spawn Cage"
    },
    {
        key: "jail_cage",
        displayName: "Jail Cage",
        signKeys: ["§8§lJail Cage"],
        ownershipTag: "jail_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "jail_cageE",
        equipMessage: "§bEquipped §8§lJail Cage"
    },
    {
        key: "gay_cage",
        displayName: "RGB Cage",
        signKeys: ["§d§lRGB Cage"],
        ownershipTag: "gay_cage",
        requiresCoins: true,
        requiresWins: false,
        category: "cages",
        equipTag: "gay_cageE",
        equipMessage: "§bEquipped §d§lRGB Cage"
    },
    {
        key: "antimass_spectrometer_cage",
        displayName: "Anit-mass Spectrometer",
        signKeys: ["§6§o§lAnit-mass Spectrometer"],
        ownershipTag: "antimass_spectrometer_cage",
        requiresCoins: true,
        requiresWins: true,
        requiresVip: true,
        category: "cages",
        equipTag: "antimass_spectrometer_cageE",
        equipMessage: "§bEquipped §6§o§lAnit-mass Spectrometer"
    },
    {
        key: "heavenly_cage",
        displayName: "Heavenly Cage",
        signKeys: ["§b§o§lHeavenly Cage"],
        ownershipTag: "heavenly_cage",
        requiresCoins: true,
        requiresWins: true,
        requiresVip: true,
        category: "cages",
        equipTag: "heavenly_cageE",
        equipMessage: "§bEquipped §b§o§lHeavenly Cage"
    }
];

export const CATEGORY_ORDER = [
    "swords", "pickaxes", "axes", "shovels", "spears",
    "armor", "potions", "blocks", "equipments",
    "vip", "megavip", "brrtech", "cages", "passes"
];

export const CATEGORY_DISPLAY = {
    swords: { displayName: "§f§lSwords", icon: "textures/items/diamond_sword" },
    pickaxes: { displayName: "§f§lPickaxes", icon: "textures/items/diamond_pickaxe" },
    axes: { displayName: "§f§lAxes", icon: "textures/items/diamond_axe" },
    shovels: { displayName: "§f§lShovels", icon: "textures/items/diamond_shovel" },
    spears: { displayName: "§f§lSpears", icon: "textures/items/trident" },
    armor: { displayName: "§f§lArmor", icon: "textures/items/diamond_chestplate" },
    potions: { displayName: "§f§lPotions", icon: "textures/items/potion_bottle_splash_heal" },
    blocks: { displayName: "§f§lBlocks", icon: "textures/blocks/grass_side_carried" },
    equipments: { displayName: "§f§lEquipment", icon: "textures/items/bow_standby" },
    vip: { displayName: "§e§l§oV.§gI.§6P.", icon: "textures/items/gold_ingot" },
    megavip: { displayName: "§l§o§aM§2E§sG§bA §sV.§2I.§aP.", icon: "textures/items/nether_star" },
    brrtech: { displayName: "§g§lBRR Tech", icon: "textures/items/breeze_rod" },
    cages: { displayName: "§b§lCages", icon: "textures/blocks/glass" },
    passes: { displayName: "§f§lPasses", icon: "textures/items/name_tag" },
};

// Prices are placeholder values - adjust to match your intended economy
export const SHOP_PRICES = {
    // Swords
    wooden_sword: { coinCost: 25, winsCost: 0 },
    copper_sword: { coinCost: 75, winsCost: 0 },
    stone_sword: { coinCost: 150, winsCost: 0 },
    gold_sword: { coinCost: 225, winsCost: 0 },
    iron_sword: { coinCost: 350, winsCost: 0 },
    diamond_sword: { coinCost: 1000, winsCost: 25 },
    netherite_sword: { coinCost: 5000, winsCost: 125 },
    // Pickaxes
    wooden_pickaxe: { coinCost: 25, winsCost: 0 },
    copper_pickaxe: { coinCost: 75, winsCost: 0 },
    stone_pickaxe: { coinCost: 150, winsCost: 0 },
    gold_pickaxe: { coinCost: 225, winsCost: 0 },
    iron_pickaxe: { coinCost: 350, winsCost: 0 },
    diamond_pickaxe: { coinCost: 1000, winsCost: 25 },
    netherite_pickaxe: { coinCost: 2000, winsCost: 125 },
    // Axes
    wooden_axe: { coinCost: 25, winsCost: 0 },
    copper_axe: { coinCost: 75, winsCost: 0 },
    stone_axe: { coinCost: 150, winsCost: 0 },
    gold_axe: { coinCost: 225, winsCost: 0 },
    iron_axe: { coinCost: 350, winsCost: 0 },
    diamond_axe: { coinCost: 1000, winsCost: 25 },
    netherite_axe: { coinCost: 5000, winsCost: 125 },
    // Shovels
    wooden_shovel: { coinCost: 25, winsCost: 0 },
    copper_shovel: { coinCost: 75, winsCost: 0 },
    stone_shovel: { coinCost: 150, winsCost: 0 },
    gold_shovel: { coinCost: 225, winsCost: 0 },
    iron_shovel: { coinCost: 350, winsCost: 0 },
    diamond_shovel: { coinCost: 1000, winsCost: 25 },
    netherite_shovel: { coinCost: 5000, winsCost: 125 },
    // Spears
    wooden_spear: { coinCost: 25, winsCost: 0 },
    copper_spear: { coinCost: 75, winsCost: 0 },
    stone_spear: { coinCost: 150, winsCost: 0 },
    gold_spear: { coinCost: 225, winsCost: 0 },
    iron_spear: { coinCost: 350, winsCost: 0 },
    diamond_spear: { coinCost: 1000, winsCost: 25 },
    netherite_spear: { coinCost: 5000, winsCost: 125 },
    // Armor (wins-based)
    leather_armor: { coinCost: 0, winsCost: 2 },
    copper_armor: { coinCost: 0, winsCost: 9 },
    chainmail_armor: { coinCost: 0, winsCost: 15 },
    gold_armor: { coinCost: 0, winsCost: 25 },
    iron_armor: { coinCost: 0, winsCost: 40 },
    diamond_armor: { coinCost: 0, winsCost: 80 },
    netherite_armor: { coinCost: 0, winsCost: 125 },
    crystal_armor: { coinCost: 0, winsCost: 250, description: "Something nice" },
    enchanted_gold_armor: { coinCost: 0, winsCost: 0, description: "Something good? :P" },
    god_armor: { coinCost: 0, winsCost: 320, description: "God had no hand in making this thing." },
    // Potions
    speed_potion: { coinCost: 50, winsCost: 0, description: "Gotta go fast" },
    jump_potion: { coinCost: 50, winsCost: 0, description: "+1 block" },
    strength_potion: { coinCost: 1800, winsCost: 0, description: "Termnator" },
    health_potion: { coinCost: 150, winsCost: 0, description: "hmmmm +4 hearts" },
    damage_potion: { coinCost: 250, winsCost: 0, description: "Just a scratch" },
    poison_potion: { coinCost: 2250, winsCost: 15, description: "Bonnie's favourite" },
    wither_potion: { coinCost: 1500, winsCost: 15, description: "Gas chamber" },
    regeneration_potion: { coinCost: 1000, winsCost: 10, description: "Restore the missing aspect" },
    turtlemaster_potion: { coinCost: 3250, winsCost: 50, description: "Ammo sponge" },
    invisibility_potion: { coinCost: 8000, winsCost: 150, description: "Sneaky" },
    // Blocks
    grass_block: { coinCost: 100, winsCost: 0 },
    glass_block: { coinCost: 100, winsCost: 0 },
    planks_block: { coinCost: 200, winsCost: 0 },
    dev_block: { coinCost: 200, winsCost: 0 },
    leaves_block: { coinCost: 100, winsCost: 0 },
    cobblestone_block: { coinCost: 200, winsCost: 0 },
    wool_block: { coinCost: 100, winsCost: 0 },
    obsidian_block: { coinCost: 800, winsCost: 25 },
    rgb_blocks: { coinCost: 0, winsCost: 0, description: "Party mode" },
    // Equipment
    bow: { coinCost: 1800, winsCost: 25 },
    shield: { coinCost: 600, winsCost: 0 },
    totem: { coinCost: 2500, winsCost: 0 },
    snowball: { coinCost: 350, winsCost: 0 },
    milk: { coinCost: 50, winsCost: 0 },
    flint_and_steel: { coinCost: 750, winsCost: 0 },
    shears: { coinCost: 50, winsCost: 0 },
    furnace: { coinCost: 5, winsCost: 0 },
    trident: { coinCost: 7500, winsCost: 150 },
    mace: { coinCost: 11250, winsCost: 175, description: "Dino's favourite" },
    // VIP pickaxe/armor (free perks)
    enchanted_gold_pickaxe: { coinCost: 0, winsCost: 0, description: "VIP exclusive" },
    // VIP items
    ender_pearl: { coinCost: 6450, winsCost: 95 },
    wind_charge: { coinCost: 3500, winsCost: 65 },
    golden_apple: { coinCost: 5000, winsCost: 0 },
    enchanted_golden_apple: { coinCost: 10000, winsCost: 76 },
    // Mega VIP
    elytra: { coinCost: 6000, winsCost: 100, description: "Mega VIP exclusive" },
    // BRR Tech
    gluon_gun: { coinCost: 45000, winsCost: 400 },
    tau_cannon: { coinCost: 31650, winsCost: 270 },
    hive_hand: { coinCost: 11345, winsCost: 100 },
    glock17: { coinCost: 3000, winsCost: 25 },
    crowbar: { coinCost: 500, winsCost: 5 },
    // Passes
    vip: { coinCost: 5000, winsCost: 25, description: "x2 coins and haste 1" },
    mega_vip: { coinCost: 20000, winsCost: 125, description: "x3 coins, haste 2 and +2 hearts permamently" },
    // Cages
    default_cage: { coinCost: 0, winsCost: 0, description: "by BonnieRobloxRIP" },
    purple_cage: { coinCost: 50, winsCost: 0, description: "by BonnieRobloxRIP" },
    fire_cage: { coinCost: 100, winsCost: 0, description: "by BonnieRobloxRIP" },
    dev_cage: { coinCost: 401, winsCost: 0, description: "by BonnieRobloxRIP" },
    nether_cage: { coinCost: 500, winsCost: 0, description: "by BonnieRobloxRIP" },
    fish_tank_cage: { coinCost: 500, winsCost: 0, description: "by BonnieRobloxRIP" },
    amethyst_cage: { coinCost: 1250, winsCost: 5, description: "by BonnieRobloxRIP" },
    cherry_blossom_cage: { coinCost: 1250, winsCost: 10, description: "by BonnieRobloxRIP" },
    mini_island_cage: { coinCost: 1250, winsCost: 10, description: "by BonnieRobloxRIP" },
    ancient_city_cage: { coinCost: 1500, winsCost: 10, description: "by FZtheDesigner" },
    diamond_sword_cage: { coinCost: 1500, winsCost: 10, description: "by DinoDanie21" },
    copper_airship_cage: { coinCost: 600, winsCost: 0, description: "by DinoDanie21" },
    bassalting_floater_cage: { coinCost: 550, winsCost: 0, description: "by DinoDanie21" },
    azalea_tree_cage: { coinCost: 1250, winsCost: 5, description: "by Marshmallow997" },
    candy_land_cage: { coinCost: 150, winsCost: 0 },
    eaten_cage: { coinCost: 150, winsCost: 0 },
    spruce_tree: { coinCost: 350, winsCost: 0, description: "by DinoDanie21" },
    bamboo_forest: { coinCost: 550, winsCost: 0, description: "by DinoDanie21" },
    spawn_cage: { coinCost: 900, winsCost: 0, description: "by BonnieRobloxRIP" },
    jail_cage: { coinCost: 750, winsCost: 0, description: "by DinoDanie21" },
    gay_cage: { coinCost: 200, winsCost: 0, description: "by DinoDanie21" },
    antimass_spectrometer_cage: { coinCost: 10000, winsCost: 50, description: "by BonnieRobloxRIP" },
    heavenly_cage: { coinCost: 5000, winsCost: 45, description: "by DinoDanie21" }
};