# = SCORES =
execute if score start easy matches 1 run scoreboard players add lift easy 1
execute if score start easy matches 1 run scoreboard players add alarm easy 1
execute if score reset easy matches 1 run scoreboard players remove lift easy 1
# = CORE EVENTS IN ORDER =
# // - sound effects -
execute if score lift easy matches 1 run playsound sfx.alarm.lift @a 8 91 52
# // silo door open
execute if score lift easy matches 350 run playsound silo_door.open @a 8 -34 52
execute if score lift easy matches 410 run stopsound @a silo_door.open
execute if score lift easy matches 410 run playsound silo_door.opened @a 8 -35 52
# // silo door close
execute if score lift easy matches 644 run playsound silo_door.open @a 8 -34 52
execute if score lift easy matches 704 run stopsound @a silo_door.open
execute if score lift easy matches 704 run playsound silo_door.opened @a 8 -35 52
# // - lift door -
# // shut the main door (as if it matters lol, they can jump over it)
execute if score lift easy matches 1 run structure load "easy:EasyLiftDoor2" 6 89 49
execute if score lift easy matches 15 run structure load "easy:EasyLiftDoor1" 6 89 49
# // open the door after the lift has risen again
execute if score lift easy matches 940 run structure load "easy:EasyLiftDoor2" 6 89 49
execute if score lift easy matches 955 run structure load "easy:EasyLiftDoor3" 6 89 49
# // lower the elevator
execute if score lift easy matches 25 run structure load "lobby/elevators:MainElevator" 6 86 50
execute if score lift easy matches 45 run structure load "lobby/elevators:MainElevator" 6 85 50
execute if score lift easy matches 55 run structure load "lobby/elevators:MainElevator" 6 84 50
execute if score lift easy matches 65 run structure load "lobby/elevators:MainElevator" 6 83 50
execute if score lift easy matches 75 run structure load "lobby/elevators:MainElevator" 6 82 50
execute if score lift easy matches 84 run structure load "lobby/elevators:MainElevator" 6 81 50
execute if score lift easy matches 92 run structure load "lobby/elevators:MainElevator" 6 80 50
execute if score lift easy matches 100 run structure load "lobby/elevators:MainElevator" 6 79 50
execute if score lift easy matches 105 run structure load "lobby/elevators:MainElevator" 6 78 50
execute if score lift easy matches 110 run structure load "lobby/elevators:MainElevator" 6 77 50
execute if score lift easy matches 115 run structure load "lobby/elevators:MainElevator" 6 76 50
execute if score lift easy matches 120 run structure load "lobby/elevators:MainElevator" 6 75 50
execute if score lift easy matches 124 run structure load "lobby/elevators:MainElevator" 6 74 50
execute if score lift easy matches 128 run structure load "lobby/elevators:MainElevator" 6 73 50
execute if score lift easy matches 132 run structure load "lobby/elevators:MainElevator" 6 72 50
execute if score lift easy matches 136 run structure load "lobby/elevators:MainElevator" 6 71 50
execute if score lift easy matches 140 run structure load "lobby/elevators:MainElevator" 6 70 50
execute if score lift easy matches 144 run structure load "lobby/elevators:MainElevator" 6 69 50
execute if score lift easy matches 148 run structure load "lobby/elevators:MainElevator" 6 68 50
execute if score lift easy matches 152 run structure load "lobby/elevators:MainElevator" 6 67 50
execute if score lift easy matches 156 run structure load "lobby/elevators:MainElevator" 6 66 50
execute if score lift easy matches 160 run structure load "lobby/elevators:MainElevator" 6 65 50
execute if score lift easy matches 163 run structure load "lobby/elevators:MainElevator" 6 64 50
execute if score lift easy matches 166 run structure load "lobby/elevators:MainElevator" 6 63 50
execute if score lift easy matches 169 run structure load "lobby/elevators:MainElevator" 6 62 50
execute if score lift easy matches 172 run structure load "lobby/elevators:MainElevator" 6 61 50
execute if score lift easy matches 175 run structure load "lobby/elevators:MainElevator" 6 60 50
execute if score lift easy matches 178 run structure load "lobby/elevators:MainElevator" 6 59 50
execute if score lift easy matches 181 run structure load "lobby/elevators:MainElevator" 6 58 50
execute if score lift easy matches 184 run structure load "lobby/elevators:MainElevator" 6 57 50
execute if score lift easy matches 187 run structure load "lobby/elevators:MainElevator" 6 56 50
execute if score lift easy matches 190 run structure load "lobby/elevators:MainElevator" 6 55 50
execute if score lift easy matches 193 run structure load "lobby/elevators:MainElevator" 6 54 50
execute if score lift easy matches 196 run structure load "lobby/elevators:MainElevator" 6 53 50
execute if score lift easy matches 199 run structure load "lobby/elevators:MainElevator" 6 52 50
execute if score lift easy matches 201 run structure load "lobby/elevators:MainElevator" 6 51 50
execute if score lift easy matches 203 run structure load "lobby/elevators:MainElevator" 6 50 50
execute if score lift easy matches 205 run structure load "lobby/elevators:MainElevator" 6 49 50
execute if score lift easy matches 207 run structure load "lobby/elevators:MainElevator" 6 48 50
execute if score lift easy matches 209 run structure load "lobby/elevators:MainElevator" 6 47 50
execute if score lift easy matches 211 run structure load "lobby/elevators:MainElevator" 6 46 50
execute if score lift easy matches 213 run structure load "lobby/elevators:MainElevator" 6 45 50
execute if score lift easy matches 215 run structure load "lobby/elevators:MainElevator" 6 44 50
execute if score lift easy matches 217 run structure load "lobby/elevators:MainElevator" 6 43 50
execute if score lift easy matches 219 run structure load "lobby/elevators:MainElevator" 6 42 50
execute if score lift easy matches 221 run structure load "lobby/elevators:MainElevator" 6 41 50
execute if score lift easy matches 223 run structure load "lobby/elevators:MainElevator" 6 40 50
execute if score lift easy matches 225 run structure load "lobby/elevators:MainElevator" 6 39 50
execute if score lift easy matches 227 run structure load "lobby/elevators:MainElevator" 6 38 50
execute if score lift easy matches 229 run structure load "lobby/elevators:MainElevator" 6 37 50
execute if score lift easy matches 231 run structure load "lobby/elevators:MainElevator" 6 36 50
execute if score lift easy matches 233 run structure load "lobby/elevators:MainElevator" 6 35 50
execute if score lift easy matches 235 run structure load "lobby/elevators:MainElevator" 6 34 50
execute if score lift easy matches 237 run structure load "lobby/elevators:MainElevator" 6 33 50
execute if score lift easy matches 239 run structure load "lobby/elevators:MainElevator" 6 32 50
execute if score lift easy matches 241 run structure load "lobby/elevators:MainElevator" 6 31 50
execute if score lift easy matches 243 run structure load "lobby/elevators:MainElevator" 6 30 50
execute if score lift easy matches 245 run structure load "lobby/elevators:MainElevator" 6 29 50
execute if score lift easy matches 247 run structure load "lobby/elevators:MainElevator" 6 28 50
execute if score lift easy matches 249 run structure load "lobby/elevators:MainElevator" 6 27 50
execute if score lift easy matches 251 run structure load "lobby/elevators:MainElevator" 6 26 50
execute if score lift easy matches 253 run structure load "lobby/elevators:MainElevator" 6 25 50
execute if score lift easy matches 255 run structure load "lobby/elevators:MainElevator" 6 24 50
execute if score lift easy matches 257 run structure load "lobby/elevators:MainElevator" 6 23 50
execute if score lift easy matches 259 run structure load "lobby/elevators:MainElevator" 6 22 50
execute if score lift easy matches 261 run structure load "lobby/elevators:MainElevator" 6 21 50
# // - entering the gamemode shaft
execute if score lift easy matches 263 run function game_functions/mode_easy/decider
execute if score lift easy matches 263 run structure load "lobby/elevators:MainElevator" 6 20 50
execute if score lift easy matches 265 run structure load "lobby/elevators:MainElevator" 6 19 50
execute if score lift easy matches 267 run structure load "lobby/elevators:MainElevator" 6 18 50
execute if score lift easy matches 269 run structure load "lobby/elevators:MainElevator" 6 17 50
execute if score lift easy matches 272 run structure load "lobby/elevators:MainElevator" 6 16 50
execute if score lift easy matches 275 run structure load "lobby/elevators:MainElevator" 6 15 50
execute if score lift easy matches 278 run structure load "lobby/elevators:MainElevator" 6 14 50
execute if score lift easy matches 281 run structure load "lobby/elevators:MainElevator" 6 13 50
execute if score lift easy matches 284 run structure load "lobby/elevators:MainElevator" 6 12 50
execute if score lift easy matches 287 run structure load "lobby/elevators:MainElevator" 6 11 50
execute if score lift easy matches 290 run structure load "lobby/elevators:MainElevator" 6 10 50
execute if score lift easy matches 293 run structure load "lobby/elevators:MainElevator" 6 9 50
execute if score lift easy matches 296 run structure load "lobby/elevators:MainElevator" 6 8 50
execute if score lift easy matches 299 run structure load "lobby/elevators:MainElevator" 6 7 50
execute if score lift easy matches 302 run structure load "lobby/elevators:MainElevator" 6 6 50
execute if score lift easy matches 305 run structure load "lobby/elevators:MainElevator" 6 5 50
execute if score lift easy matches 308 run structure load "lobby/elevators:MainElevator" 6 4 50
execute if score lift easy matches 311 run structure load "lobby/elevators:MainElevator" 6 3 50
execute if score lift easy matches 314 run structure load "lobby/elevators:MainElevator" 6 2 50
execute if score lift easy matches 317 run structure load "lobby/elevators:MainElevator" 6 1 50
execute if score lift easy matches 320 run structure load "lobby/elevators:MainElevator" 6 0 50
execute if score lift easy matches 323 run structure load "lobby/elevators:MainElevator" 6 -1 50
execute if score lift easy matches 326 run structure load "lobby/elevators:MainElevator" 6 -2 50
execute if score lift easy matches 329 run structure load "lobby/elevators:MainElevator" 6 -3 50
execute if score lift easy matches 332 run structure load "lobby/elevators:MainElevator" 6 -4 50
execute if score lift easy matches 335 run structure load "lobby/elevators:MainElevator" 6 -5 50
execute if score lift easy matches 338 run structure load "lobby/elevators:MainElevator" 6 -6 50
execute if score lift easy matches 341 run structure load "lobby/elevators:MainElevator" 6 -7 50
execute if score lift easy matches 344 run structure load "lobby/elevators:MainElevator" 6 -8 50
execute if score lift easy matches 347 run structure load "lobby/elevators:MainElevator" 6 -9 50
execute if score lift easy matches 350 run structure load "lobby/elevators:MainElevator" 6 -10 50
execute if score lift easy matches 353 run structure load "lobby/elevators:MainElevator" 6 -11 50
execute if score lift easy matches 356 run structure load "lobby/elevators:MainElevator" 6 -12 50
execute if score lift easy matches 359 run structure load "lobby/elevators:MainElevator" 6 -13 50
execute if score lift easy matches 362 run structure load "lobby/elevators:MainElevator" 6 -14 50
execute if score lift easy matches 365 run structure load "lobby/elevators:MainElevator" 6 -15 50
execute if score lift easy matches 368 run structure load "lobby/elevators:MainElevator" 6 -16 50
execute if score lift easy matches 371 run structure load "lobby/elevators:MainElevator" 6 -17 50
execute if score lift easy matches 374 run structure load "lobby/elevators:MainElevator" 6 -18 50
execute if score lift easy matches 377 run structure load "lobby/elevators:MainElevator" 6 -19 50
execute if score lift easy matches 380 run structure load "lobby/elevators:MainElevator" 6 -20 50
execute if score lift easy matches 384 run structure load "lobby/elevators:MainElevator" 6 -21 50
execute if score lift easy matches 388 run structure load "lobby/elevators:MainElevator" 6 -22 50
execute if score lift easy matches 392 run structure load "lobby/elevators:MainElevator" 6 -23 50
execute if score lift easy matches 396 run structure load "lobby/elevators:MainElevator" 6 -24 50
execute if score lift easy matches 400 run structure load "lobby/elevators:MainElevator" 6 -25 50
execute if score lift easy matches 404 run structure load "lobby/elevators:MainElevator" 6 -26 50
execute if score lift easy matches 408 run structure load "lobby/elevators:MainElevator" 6 -27 50
execute if score lift easy matches 412 run structure load "lobby/elevators:MainElevator" 6 -28 50
execute if score lift easy matches 418 run structure load "lobby/elevators:MainElevator" 6 -29 50
execute if score lift easy matches 424 run structure load "lobby/elevators:MainElevator" 6 -30 50
execute if score lift easy matches 428 run structure load "lobby/elevators:MainElevator" 6 -31 50
execute if score lift easy matches 435 run structure load "lobby/elevators:MainElevator" 6 -32 50
execute if score lift easy matches 440 run structure load "lobby/elevators:MainElevator" 6 -33 50
execute if score lift easy matches 445 run structure load "lobby/elevators:MainElevator" 6 -34 50
execute if score lift easy matches 450 run structure load "lobby/elevators:MainElevator" 6 -35 50
# // Entering Room 1
execute if score lift easy matches 455 run structure load "lobby:LiftBorderPrecaution" 5 -59 49
execute if score lift easy matches 455 run structure load "lobby/elevators:MainElevator" 6 -36 50
execute if score lift easy matches 460 run structure load "lobby/elevators:MainElevator" 6 -37 50
execute if score lift easy matches 465 run structure load "lobby/elevators:MainElevator" 6 -38 50
execute if score lift easy matches 470 run structure load "lobby/elevators:MainElevator" 6 -39 50
execute if score lift easy matches 475 run structure load "lobby/elevators:MainElevator" 6 -40 50
execute if score lift easy matches 480 run structure load "lobby/elevators:MainElevator" 6 -41 50
execute if score lift easy matches 485 run structure load "lobby/elevators:MainElevator" 6 -42 50
execute if score lift easy matches 495 run structure load "lobby/elevators:MainElevator" 6 -43 50
execute if score lift easy matches 505 run structure load "lobby/elevators:MainElevator" 6 -44 50
execute if score lift easy matches 520 run structure load "lobby/elevators:MainElevator" 6 -45 50
# // Release players
execute if score lift easy matches 530 run playsound sfx.doors.liftsepparate @a 8 -49 52
execute if score lift easy matches 530 run structure load "lobby/elevators:MainElevatorOpen1" 6 -49 50
execute if score lift easy matches 532 run structure load "lobby/elevators:MainElevatorOpen2" 6 -49 50
execute if score lift easy matches 534 run structure load "lobby/elevators:MainElevatorOpen3" 6 -49 50
execute if score lift easy matches 538 run structure load "lobby/elevators:MainElevatorOpen2" 6 -49 50
execute if score lift easy matches 540 run structure load "lobby/elevators:MainElevatorOpen3" 6 -49 50
# // begin game
execute if score lift easy matches 540 run scoreboard players set started easy 1
# // Raise elevator back to the surface
execute if score lift easy matches 550 run structure load "lobby/elevators:MainElevatorOpen3" 6 -48 50
execute if score lift easy matches 560 run structure load "lobby/elevators:MainElevatorOpen3" 6 -47 50
execute if score lift easy matches 565 run structure load "lobby:LiftBorderRemove" 5 -59 49
execute if score lift easy matches 570 run structure load "lobby/elevators:MainElevatorOpen3" 6 -46 50
execute if score lift easy matches 578 run structure load "lobby/elevators:MainElevatorOpen3" 6 -45 50
execute if score lift easy matches 585 run structure load "lobby/elevators:MainElevatorOpen3" 6 -44 50
execute if score lift easy matches 592 run structure load "lobby/elevators:MainElevatorOpen3" 6 -43 50
execute if score lift easy matches 600 run structure load "lobby/elevators:MainElevatorOpen3" 6 -42 50
execute if score lift easy matches 605 run structure load "lobby/elevators:MainElevatorOpen3" 6 -41 50
execute if score lift easy matches 610 run structure load "lobby/elevators:MainElevatorOpen3" 6 -40 50
execute if score lift easy matches 615 run structure load "lobby/elevators:MainElevatorOpen3" 6 -39 50
execute if score lift easy matches 620 run structure load "lobby/elevators:MainElevatorOpen3" 6 -38 50
execute if score lift easy matches 625 run structure load "lobby/elevators:MainElevatorOpen3" 6 -37 50
execute if score lift easy matches 630 run structure load "lobby/elevators:MainElevatorOpen3" 6 -36 50
execute if score lift easy matches 635 run structure load "lobby/elevators:MainElevatorOpen3" 6 -35 50
# // Exiting Room 1
execute if score lift easy matches 640 run structure load "lobby/elevators:MainElevatorOpen3" 6 -35 50
execute if score lift easy matches 644 run structure load "lobby/elevators:MainElevatorOpen3" 6 -34 50
execute if score lift easy matches 648 run structure load "lobby/elevators:MainElevatorOpen3" 6 -33 50
execute if score lift easy matches 652 run structure load "lobby/elevators:MainElevatorOpen3" 6 -32 50
execute if score lift easy matches 655 run structure load "lobby/elevators:MainElevatorOpen3" 6 -31 50
execute if score lift easy matches 658 run structure load "lobby/elevators:MainElevatorOpen3" 6 -30 50
execute if score lift easy matches 661 run structure load "lobby/elevators:MainElevatorOpen3" 6 -29 50
execute if score lift easy matches 664 run structure load "lobby/elevators:MainElevatorOpen3" 6 -28 50
execute if score lift easy matches 667 run structure load "lobby/elevators:MainElevatorOpen3" 6 -27 50
execute if score lift easy matches 670 run structure load "lobby/elevators:MainElevatorOpen3" 6 -26 50
execute if score lift easy matches 673 run structure load "lobby/elevators:MainElevatorOpen3" 6 -25 50
execute if score lift easy matches 676 run structure load "lobby/elevators:MainElevatorOpen3" 6 -24 50
execute if score lift easy matches 679 run structure load "lobby/elevators:MainElevatorOpen3" 6 -23 50
execute if score lift easy matches 682 run structure load "lobby/elevators:MainElevatorOpen3" 6 -22 50
execute if score lift easy matches 685 run structure load "lobby/elevators:MainElevatorOpen3" 6 -21 50
execute if score lift easy matches 688 run structure load "lobby/elevators:MainElevatorOpen3" 6 -20 50
execute if score lift easy matches 691 run structure load "lobby/elevators:MainElevatorOpen3" 6 -19 50
execute if score lift easy matches 693 run structure load "lobby/elevators:MainElevatorOpen3" 6 -18 50
execute if score lift easy matches 695 run structure load "lobby/elevators:MainElevatorOpen3" 6 -17 50
execute if score lift easy matches 697 run structure load "lobby/elevators:MainElevatorOpen3" 6 -16 50
execute if score lift easy matches 699 run structure load "lobby/elevators:MainElevatorOpen3" 6 -15 50
execute if score lift easy matches 701 run structure load "lobby/elevators:MainElevatorOpen3" 6 -14 50
execute if score lift easy matches 703 run structure load "lobby/elevators:MainElevatorOpen3" 6 -13 50
execute if score lift easy matches 705 run structure load "lobby/elevators:MainElevatorOpen3" 6 -12 50
execute if score lift easy matches 707 run structure load "lobby/elevators:MainElevatorOpen3" 6 -11 50
execute if score lift easy matches 709 run structure load "lobby/elevators:MainElevatorOpen3" 6 -10 50
execute if score lift easy matches 711 run structure load "lobby/elevators:MainElevatorOpen3" 6 -9 50
execute if score lift easy matches 713 run structure load "lobby/elevators:MainElevatorOpen3" 6 -8 50
execute if score lift easy matches 715 run structure load "lobby/elevators:MainElevatorOpen3" 6 -7 50
execute if score lift easy matches 717 run structure load "lobby/elevators:MainElevatorOpen3" 6 -6 50
execute if score lift easy matches 719 run structure load "lobby/elevators:MainElevatorOpen3" 6 -5 50
execute if score lift easy matches 722 run structure load "lobby/elevators:MainElevatorOpen3" 6 -4 50
execute if score lift easy matches 724 run structure load "lobby/elevators:MainElevatorOpen3" 6 -3 50
execute if score lift easy matches 726 run structure load "lobby/elevators:MainElevatorOpen3" 6 -2 50
execute if score lift easy matches 728 run structure load "lobby/elevators:MainElevatorOpen3" 6 -1 50
execute if score lift easy matches 730 run structure load "lobby/elevators:MainElevatorOpen3" 6 0 50
execute if score lift easy matches 732 run structure load "lobby/elevators:MainElevatorOpen3" 6 1 50
execute if score lift easy matches 734 run structure load "lobby/elevators:MainElevatorOpen3" 6 2 50
execute if score lift easy matches 736 run structure load "lobby/elevators:MainElevatorOpen3" 6 3 50
execute if score lift easy matches 738 run structure load "lobby/elevators:MainElevatorOpen3" 6 4 50
execute if score lift easy matches 740 run structure load "lobby/elevators:MainElevatorOpen3" 6 5 50
execute if score lift easy matches 741 run structure load "lobby/elevators:MainElevatorOpen3" 6 6 50
execute if score lift easy matches 742 run structure load "lobby/elevators:MainElevatorOpen3" 6 7 50
execute if score lift easy matches 743 run structure load "lobby/elevators:MainElevatorOpen3" 6 8 50
execute if score lift easy matches 744 run structure load "lobby/elevators:MainElevatorOpen3" 6 9 50
execute if score lift easy matches 745 run structure load "lobby/elevators:MainElevatorOpen3" 6 10 50
execute if score lift easy matches 746 run structure load "lobby/elevators:MainElevatorOpen3" 6 11 50
execute if score lift easy matches 747 run structure load "lobby/elevators:MainElevatorOpen3" 6 12 50
execute if score lift easy matches 748 run structure load "lobby/elevators:MainElevatorOpen3" 6 13 50
execute if score lift easy matches 749 run structure load "lobby/elevators:MainElevatorOpen3" 6 14 50
execute if score lift easy matches 750 run structure load "lobby/elevators:MainElevatorOpen3" 6 15 50
execute if score lift easy matches 751 run structure load "lobby/elevators:MainElevatorOpen3" 6 16 50
execute if score lift easy matches 752 run structure load "lobby/elevators:MainElevatorOpen3" 6 17 50
execute if score lift easy matches 753 run structure load "lobby/elevators:MainElevatorOpen3" 6 18 50
execute if score lift easy matches 754 run structure load "lobby/elevators:MainElevatorOpen3" 6 19 50
execute if score lift easy matches 755 run structure load "lobby/elevators:MainElevatorOpen3" 6 20 50
# // Exiting Gamemode Shaft
execute if score lift easy matches 756 run structure load "lobby/elevators:MainElevatorOpen3" 6 21 50
execute if score lift easy matches 757 run structure load "lobby/elevators:MainElevatorOpen3" 6 22 50
execute if score lift easy matches 758 run structure load "lobby/elevators:MainElevatorOpen3" 6 23 50
execute if score lift easy matches 759 run structure load "lobby/elevators:MainElevatorOpen3" 6 24 50
execute if score lift easy matches 760 run structure load "lobby/elevators:MainElevatorOpen3" 6 25 50
execute if score lift easy matches 761 run structure load "lobby/elevators:MainElevatorOpen3" 6 26 50
execute if score lift easy matches 762 run structure load "lobby/elevators:MainElevatorOpen3" 6 27 50
execute if score lift easy matches 763 run structure load "lobby/elevators:MainElevatorOpen3" 6 28 50
execute if score lift easy matches 764 run structure load "lobby/elevators:MainElevatorOpen3" 6 29 50
execute if score lift easy matches 765 run structure load "lobby/elevators:MainElevatorOpen3" 6 30 50
execute if score lift easy matches 766 run structure load "lobby/elevators:MainElevatorOpen3" 6 31 50
execute if score lift easy matches 767 run structure load "lobby/elevators:MainElevatorOpen3" 6 32 50
execute if score lift easy matches 768 run structure load "lobby/elevators:MainElevatorOpen3" 6 33 50
execute if score lift easy matches 769 run structure load "lobby/elevators:MainElevatorOpen3" 6 34 50
execute if score lift easy matches 770 run structure load "lobby/elevators:MainElevatorOpen3" 6 35 50
execute if score lift easy matches 771 run structure load "lobby/elevators:MainElevatorOpen3" 6 36 50
execute if score lift easy matches 772 run structure load "lobby/elevators:MainElevatorOpen3" 6 37 50
execute if score lift easy matches 773 run structure load "lobby/elevators:MainElevatorOpen3" 6 38 50
execute if score lift easy matches 774 run structure load "lobby/elevators:MainElevatorOpen3" 6 39 50
execute if score lift easy matches 775 run structure load "lobby/elevators:MainElevatorOpen3" 6 40 50
execute if score lift easy matches 776 run structure load "lobby/elevators:MainElevatorOpen3" 6 41 50
execute if score lift easy matches 777 run structure load "lobby/elevators:MainElevatorOpen3" 6 42 50
execute if score lift easy matches 778 run structure load "lobby/elevators:MainElevatorOpen3" 6 43 50
execute if score lift easy matches 779 run structure load "lobby/elevators:MainElevatorOpen3" 6 44 50
execute if score lift easy matches 780 run structure load "lobby/elevators:MainElevatorOpen3" 6 45 50
execute if score lift easy matches 781 run structure load "lobby/elevators:MainElevatorOpen3" 6 46 50
execute if score lift easy matches 782 run structure load "lobby/elevators:MainElevatorOpen3" 6 47 50
execute if score lift easy matches 783 run structure load "lobby/elevators:MainElevatorOpen3" 6 48 50
execute if score lift easy matches 784 run structure load "lobby/elevators:MainElevatorOpen3" 6 49 50
execute if score lift easy matches 785 run structure load "lobby/elevators:MainElevatorOpen3" 6 50 50
execute if score lift easy matches 787 run structure load "lobby/elevators:MainElevatorOpen3" 6 51 50
execute if score lift easy matches 789 run structure load "lobby/elevators:MainElevatorOpen3" 6 52 50
execute if score lift easy matches 791 run structure load "lobby/elevators:MainElevatorOpen3" 6 53 50
execute if score lift easy matches 793 run structure load "lobby/elevators:MainElevatorOpen3" 6 54 50
execute if score lift easy matches 795 run structure load "lobby/elevators:MainElevatorOpen3" 6 55 50
execute if score lift easy matches 797 run structure load "lobby/elevators:MainElevatorOpen3" 6 56 50
execute if score lift easy matches 799 run structure load "lobby/elevators:MainElevatorOpen3" 6 57 50
execute if score lift easy matches 802 run structure load "lobby/elevators:MainElevatorOpen3" 6 58 50
execute if score lift easy matches 805 run structure load "lobby/elevators:MainElevatorOpen3" 6 59 50
execute if score lift easy matches 808 run structure load "lobby/elevators:MainElevatorOpen3" 6 60 50
execute if score lift easy matches 811 run structure load "lobby/elevators:MainElevatorOpen3" 6 61 50
execute if score lift easy matches 814 run structure load "lobby/elevators:MainElevatorOpen3" 6 62 50
execute if score lift easy matches 817 run structure load "lobby/elevators:MainElevatorOpen3" 6 63 50
execute if score lift easy matches 820 run structure load "lobby/elevators:MainElevatorOpen3" 6 64 50
execute if score lift easy matches 823 run structure load "lobby/elevators:MainElevatorOpen3" 6 65 50
execute if score lift easy matches 826 run structure load "lobby/elevators:MainElevatorOpen3" 6 66 50
execute if score lift easy matches 829 run structure load "lobby/elevators:MainElevatorOpen3" 6 67 50
execute if score lift easy matches 842 run structure load "lobby/elevators:MainElevatorOpen3" 6 68 50
execute if score lift easy matches 846 run structure load "lobby/elevators:MainElevatorOpen3" 6 69 50
execute if score lift easy matches 850 run structure load "lobby/elevators:MainElevatorOpen3" 6 70 50
execute if score lift easy matches 854 run structure load "lobby/elevators:MainElevatorOpen3" 6 71 50
execute if score lift easy matches 858 run structure load "lobby/elevators:MainElevatorOpen3" 6 72 50
execute if score lift easy matches 862 run structure load "lobby/elevators:MainElevatorOpen3" 6 73 50
execute if score lift easy matches 866 run structure load "lobby/elevators:MainElevatorOpen3" 6 74 50
execute if score lift easy matches 870 run structure load "lobby/elevators:MainElevatorOpen3" 6 75 50
execute if score lift easy matches 874 run structure load "lobby/elevators:MainElevatorOpen3" 6 76 50
execute if score lift easy matches 878 run structure load "lobby/elevators:MainElevatorOpen3" 6 77 50
execute if score lift easy matches 882 run structure load "lobby/elevators:MainElevatorOpen3" 6 78 50
execute if score lift easy matches 886 run structure load "lobby/elevators:MainElevatorOpen3" 6 79 50
execute if score lift easy matches 891 run structure load "lobby/elevators:MainElevatorOpen3" 6 80 50
execute if score lift easy matches 898 run structure load "lobby/elevators:MainElevatorOpen3" 6 81 50
execute if score lift easy matches 904 run structure load "lobby/elevators:MainElevatorOpen3" 6 82 50
execute if score lift easy matches 913 run structure load "lobby/elevators:MainElevatorOpen3" 6 83 50
# // Close the Elevator
execute if score lift easy matches 920 run structure load "lobby/elevators:MainElevatorOpen2" 6 83 50
execute if score lift easy matches 930 run structure load "lobby/elevators:MainElevatorOpen1" 6 83 50
execute if score lift easy matches 940 run structure load "lobby/elevators:MainElevator" 6 87 50
# = OTHER THINGS =
# // Silo door open
execute if score lift easy matches 350 run structure load "lobby/doors:SiloDoor2" 6 -36 47
execute if score lift easy matches 380 run structure load "lobby/doors:SiloDoor3" 6 -36 47
execute if score lift easy matches 410 run structure load "lobby/doors:SiloDoor4" 6 -36 47
# // Silo door close
execute if score lift easy matches 644 run structure load "lobby/doors:SiloDoor3" 6 -36 47
execute if score lift easy matches 674 run structure load "lobby/doors:SiloDoor2" 6 -36 47
execute if score lift easy matches 704 run structure load "lobby/doors:SiloDoor1" 6 -36 47
# = ALARM EFFECT =
execute if score alarm easy matches 1 run structure load "easy:EasyStateLower1" 5 93 49
execute if score alarm easy matches 4 run structure load "easy:EasyStateLower2" 5 93 49
execute if score alarm easy matches 7 run structure load "easy:EasyStateLower3" 5 93 49
execute if score alarm easy matches 10 run structure load "easy:EasyStateLower4" 5 93 49
execute if score alarm easy matches 13.. run scoreboard players set alarm easy 0
# // change elevator status
execute if score lift easy matches 955 run scoreboard players set start easy 2
execute if score lift easy matches 955 run structure load "easy:EasyStateBusy" 5 93 49
execute if score lift easy matches 955 if score p_game easy matches 0 run scoreboard players set reset easy 1
execute if score lift easy matches 955 run scoreboard players set lift easy 0
# = RESET =
execute if score reset easy matches 1 if score p_game easy matches 0 if score lift easy matches -40 if score start easy matches 2 run function game_functions/mode_easy/reset